syntax = "proto3";

package gateway.v1;

option go_package = "github.com/vadam-zhan/long-gw/common-protocol/gen/gateway/v1;gatewayv1";

import "gateway/v1/common.proto";

// UpstreamEvent is sent from gateway to backend
message UpstreamEvent {
    string user_id = 1;                        // 用户 ID
    string device_id = 2;                      // 设备 ID
    string biz_code = 3;                       // 业务域标识
    FrameType original_type = 4;               // 原始消息类型
    RouteTarget from = 5;                      // 发送方标识
    RouteTarget to = 6;                        // 路由地址
    Delivery delivery = 7;                     // 投递
    TraceContext trace_context = 8;            // 追踪
    map<string, string> headers = 9;           // 扩展元数据
    Body body = 10;
}

// DownstreamEvent is sent from backend to gateway
message DownstreamEvent {
    RouteTarget from = 1;                // 发送方标识
    RouteTarget to = 2;                  // 路由地址
    string biz_code = 3;                 // 业务域标识
    FrameType target_type = 4;           // 投递到客户端的消息类型
    Delivery delivery = 5;               // 投递
    TraceContext trace_context = 6;      // 追踪
    map<string, string> headers = 7;     // 扩展元数据
    Body body = 8;
}
