// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/gateway.proto

package gateway

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PushMessageReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMessageReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushMessageReqMultiError,
// or nil if none found.
func (m *PushMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Receiver

	// no validation rules for Payload

	// no validation rules for PushType

	// no validation rules for BusinessType

	if len(errors) > 0 {
		return PushMessageReqMultiError(errors)
	}

	return nil
}

// PushMessageReqMultiError is an error wrapping multiple validation errors
// returned by PushMessageReq.ValidateAll() if the designated constraints
// aren't met.
type PushMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMessageReqMultiError) AllErrors() []error { return m }

// PushMessageReqValidationError is the validation error returned by
// PushMessageReq.Validate if the designated constraints aren't met.
type PushMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMessageReqValidationError) ErrorName() string { return "PushMessageReqValidationError" }

// Error satisfies the builtin error interface
func (e PushMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMessageReqValidationError{}

// Validate checks the field values on PushMessageResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PushMessageResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMessageResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PushMessageRespMultiError, or nil if none found.
func (m *PushMessageResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMessageResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return PushMessageRespMultiError(errors)
	}

	return nil
}

// PushMessageRespMultiError is an error wrapping multiple validation errors
// returned by PushMessageResp.ValidateAll() if the designated constraints
// aren't met.
type PushMessageRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMessageRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMessageRespMultiError) AllErrors() []error { return m }

// PushMessageRespValidationError is the validation error returned by
// PushMessageResp.Validate if the designated constraints aren't met.
type PushMessageRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMessageRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMessageRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMessageRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMessageRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMessageRespValidationError) ErrorName() string { return "PushMessageRespValidationError" }

// Error satisfies the builtin error interface
func (e PushMessageRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMessageResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMessageRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMessageRespValidationError{}
