// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/kafka_message.proto

package gateway

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpstreamKafkaMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpstreamKafkaMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpstreamKafkaMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpstreamKafkaMessageMultiError, or nil if none found.
func (m *UpstreamKafkaMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *UpstreamKafkaMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CorrelationId

	// no validation rules for ConnId

	// no validation rules for UserId

	// no validation rules for DeviceId

	// no validation rules for OriginalType

	// no validation rules for Payload

	// no validation rules for Timestamp

	// no validation rules for BusinessType

	if len(errors) > 0 {
		return UpstreamKafkaMessageMultiError(errors)
	}

	return nil
}

// UpstreamKafkaMessageMultiError is an error wrapping multiple validation
// errors returned by UpstreamKafkaMessage.ValidateAll() if the designated
// constraints aren't met.
type UpstreamKafkaMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpstreamKafkaMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpstreamKafkaMessageMultiError) AllErrors() []error { return m }

// UpstreamKafkaMessageValidationError is the validation error returned by
// UpstreamKafkaMessage.Validate if the designated constraints aren't met.
type UpstreamKafkaMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpstreamKafkaMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpstreamKafkaMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpstreamKafkaMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpstreamKafkaMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpstreamKafkaMessageValidationError) ErrorName() string {
	return "UpstreamKafkaMessageValidationError"
}

// Error satisfies the builtin error interface
func (e UpstreamKafkaMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpstreamKafkaMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpstreamKafkaMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpstreamKafkaMessageValidationError{}

// Validate checks the field values on DownstreamKafkaMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DownstreamKafkaMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DownstreamKafkaMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DownstreamKafkaMessageMultiError, or nil if none found.
func (m *DownstreamKafkaMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *DownstreamKafkaMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CorrelationId

	// no validation rules for ConnId

	// no validation rules for UserId

	// no validation rules for DeviceId

	// no validation rules for TargetType

	// no validation rules for Payload

	// no validation rules for Timestamp

	// no validation rules for BusinessType

	if len(errors) > 0 {
		return DownstreamKafkaMessageMultiError(errors)
	}

	return nil
}

// DownstreamKafkaMessageMultiError is an error wrapping multiple validation
// errors returned by DownstreamKafkaMessage.ValidateAll() if the designated
// constraints aren't met.
type DownstreamKafkaMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DownstreamKafkaMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DownstreamKafkaMessageMultiError) AllErrors() []error { return m }

// DownstreamKafkaMessageValidationError is the validation error returned by
// DownstreamKafkaMessage.Validate if the designated constraints aren't met.
type DownstreamKafkaMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DownstreamKafkaMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DownstreamKafkaMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DownstreamKafkaMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DownstreamKafkaMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DownstreamKafkaMessageValidationError) ErrorName() string {
	return "DownstreamKafkaMessageValidationError"
}

// Error satisfies the builtin error interface
func (e DownstreamKafkaMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDownstreamKafkaMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DownstreamKafkaMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DownstreamKafkaMessageValidationError{}
