// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/signal.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 信令类型枚举（对应不同接口）
type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	// 核心控制信令
	// 心跳信令，用于检测连接是否存活
	SignalType_SIGNAL_TYPE_HEARTBEAT_PING SignalType = 1
	SignalType_SIGNAL_TYPE_HEARTBEAT_PONG SignalType = 2
	// 鉴权信令
	SignalType_SIGNAL_TYPE_AUTH_REQUEST  SignalType = 3
	SignalType_SIGNAL_TYPE_AUTH_RESPONSE SignalType = 4
	// 消息确认
	SignalType_SIGNAL_TYPE_MESSAGE_ACK SignalType = 5
	// 主动登出
	SignalType_SIGNAL_TYPE_LOGOUT_REQUEST  SignalType = 7
	SignalType_SIGNAL_TYPE_LOGOUT_RESPONSE SignalType = 8
	// 扩展控制信令
	SignalType_SIGNAL_TYPE_SUBSCRIBE_REQUEST    SignalType = 9 // 主题订阅请求
	SignalType_SIGNAL_TYPE_SUBSCRIBE_RESPONSE   SignalType = 10
	SignalType_SIGNAL_TYPE_UNSUBSCRIBE_REQUEST  SignalType = 11 // 主题取消订阅请求
	SignalType_SIGNAL_TYPE_UNSUBSCRIBE_RESPONSE SignalType = 12
	// 业务透传
	SignalType_SIGNAL_TYPE_BUSINESS_UP   SignalType = 100 // 业务上行消息
	SignalType_SIGNAL_TYPE_BUSINESS_DOWN SignalType = 101 // 业务下行消息
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0:   "SIGNAL_TYPE_UNSPECIFIED",
		1:   "SIGNAL_TYPE_HEARTBEAT_PING",
		2:   "SIGNAL_TYPE_HEARTBEAT_PONG",
		3:   "SIGNAL_TYPE_AUTH_REQUEST",
		4:   "SIGNAL_TYPE_AUTH_RESPONSE",
		5:   "SIGNAL_TYPE_MESSAGE_ACK",
		7:   "SIGNAL_TYPE_LOGOUT_REQUEST",
		8:   "SIGNAL_TYPE_LOGOUT_RESPONSE",
		9:   "SIGNAL_TYPE_SUBSCRIBE_REQUEST",
		10:  "SIGNAL_TYPE_SUBSCRIBE_RESPONSE",
		11:  "SIGNAL_TYPE_UNSUBSCRIBE_REQUEST",
		12:  "SIGNAL_TYPE_UNSUBSCRIBE_RESPONSE",
		100: "SIGNAL_TYPE_BUSINESS_UP",
		101: "SIGNAL_TYPE_BUSINESS_DOWN",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED":          0,
		"SIGNAL_TYPE_HEARTBEAT_PING":       1,
		"SIGNAL_TYPE_HEARTBEAT_PONG":       2,
		"SIGNAL_TYPE_AUTH_REQUEST":         3,
		"SIGNAL_TYPE_AUTH_RESPONSE":        4,
		"SIGNAL_TYPE_MESSAGE_ACK":          5,
		"SIGNAL_TYPE_LOGOUT_REQUEST":       7,
		"SIGNAL_TYPE_LOGOUT_RESPONSE":      8,
		"SIGNAL_TYPE_SUBSCRIBE_REQUEST":    9,
		"SIGNAL_TYPE_SUBSCRIBE_RESPONSE":   10,
		"SIGNAL_TYPE_UNSUBSCRIBE_REQUEST":  11,
		"SIGNAL_TYPE_UNSUBSCRIBE_RESPONSE": 12,
		"SIGNAL_TYPE_BUSINESS_UP":          100,
		"SIGNAL_TYPE_BUSINESS_DOWN":        101,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_signal_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_v1_signal_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{0}
}

type ClientSignal struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SignalType SignalType             `protobuf:"varint,1,opt,name=signal_type,json=signalType,proto3,enum=gateway.v1.SignalType" json:"signal_type,omitempty"` // 信令类型（接口标识）
	RequestId  string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                // 全链路追踪ID，必填
	SequenceId uint64                 `protobuf:"varint,3,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`                            // 单连接内单调递增序列号，防重放
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientSignal_HeartbeatPing
	//	*ClientSignal_HeartbeatPong
	//	*ClientSignal_AuthRequest
	//	*ClientSignal_AuthResponse
	//	*ClientSignal_LogoutRequest
	//	*ClientSignal_LogoutResponse
	//	*ClientSignal_SubscribeRequest
	//	*ClientSignal_SubscribeResponse
	//	*ClientSignal_UnsubscribeRequest
	//	*ClientSignal_UnsubscribeResponse
	//	*ClientSignal_MessageAck
	//	*ClientSignal_BusinessUp
	//	*ClientSignal_BusinessDown
	Payload       isClientSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	mi := &file_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *ClientSignal) GetSignalType() SignalType {
	if x != nil {
		return x.SignalType
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *ClientSignal) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientSignal) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *ClientSignal) GetPayload() isClientSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientSignal) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *ClientSignal) GetHeartbeatPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_HeartbeatPong); ok {
			return x.HeartbeatPong
		}
	}
	return nil
}

func (x *ClientSignal) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *ClientSignal) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *ClientSignal) GetLogoutRequest() *LogoutRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_LogoutRequest); ok {
			return x.LogoutRequest
		}
	}
	return nil
}

func (x *ClientSignal) GetLogoutResponse() *LogoutResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_LogoutResponse); ok {
			return x.LogoutResponse
		}
	}
	return nil
}

func (x *ClientSignal) GetSubscribeRequest() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_SubscribeRequest); ok {
			return x.SubscribeRequest
		}
	}
	return nil
}

func (x *ClientSignal) GetSubscribeResponse() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_SubscribeResponse); ok {
			return x.SubscribeResponse
		}
	}
	return nil
}

func (x *ClientSignal) GetUnsubscribeRequest() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_UnsubscribeRequest); ok {
			return x.UnsubscribeRequest
		}
	}
	return nil
}

func (x *ClientSignal) GetUnsubscribeResponse() *UnsubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_UnsubscribeResponse); ok {
			return x.UnsubscribeResponse
		}
	}
	return nil
}

func (x *ClientSignal) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *ClientSignal) GetBusinessUp() *BusinessUp {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_BusinessUp); ok {
			return x.BusinessUp
		}
	}
	return nil
}

func (x *ClientSignal) GetBusinessDown() *BusinessDown {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_BusinessDown); ok {
			return x.BusinessDown
		}
	}
	return nil
}

type isClientSignal_Payload interface {
	isClientSignal_Payload()
}

type ClientSignal_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,10,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type ClientSignal_HeartbeatPong struct {
	HeartbeatPong *HeartbeatPong `protobuf:"bytes,11,opt,name=heartbeat_pong,json=heartbeatPong,proto3,oneof"`
}

type ClientSignal_AuthRequest struct {
	AuthRequest *AuthRequest `protobuf:"bytes,12,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type ClientSignal_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,13,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type ClientSignal_LogoutRequest struct {
	LogoutRequest *LogoutRequest `protobuf:"bytes,14,opt,name=logout_request,json=logoutRequest,proto3,oneof"`
}

type ClientSignal_LogoutResponse struct {
	LogoutResponse *LogoutResponse `protobuf:"bytes,15,opt,name=logout_response,json=logoutResponse,proto3,oneof"`
}

type ClientSignal_SubscribeRequest struct {
	SubscribeRequest *SubscribeRequest `protobuf:"bytes,16,opt,name=subscribe_request,json=subscribeRequest,proto3,oneof"`
}

type ClientSignal_SubscribeResponse struct {
	SubscribeResponse *SubscribeResponse `protobuf:"bytes,17,opt,name=subscribe_response,json=subscribeResponse,proto3,oneof"`
}

type ClientSignal_UnsubscribeRequest struct {
	UnsubscribeRequest *UnsubscribeRequest `protobuf:"bytes,18,opt,name=unsubscribe_request,json=unsubscribeRequest,proto3,oneof"`
}

type ClientSignal_UnsubscribeResponse struct {
	UnsubscribeResponse *UnsubscribeResponse `protobuf:"bytes,19,opt,name=unsubscribe_response,json=unsubscribeResponse,proto3,oneof"`
}

type ClientSignal_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,99,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type ClientSignal_BusinessUp struct {
	BusinessUp *BusinessUp `protobuf:"bytes,100,opt,name=business_up,json=businessUp,proto3,oneof"`
}

type ClientSignal_BusinessDown struct {
	BusinessDown *BusinessDown `protobuf:"bytes,101,opt,name=business_down,json=businessDown,proto3,oneof"`
}

func (*ClientSignal_HeartbeatPing) isClientSignal_Payload() {}

func (*ClientSignal_HeartbeatPong) isClientSignal_Payload() {}

func (*ClientSignal_AuthRequest) isClientSignal_Payload() {}

func (*ClientSignal_AuthResponse) isClientSignal_Payload() {}

func (*ClientSignal_LogoutRequest) isClientSignal_Payload() {}

func (*ClientSignal_LogoutResponse) isClientSignal_Payload() {}

func (*ClientSignal_SubscribeRequest) isClientSignal_Payload() {}

func (*ClientSignal_SubscribeResponse) isClientSignal_Payload() {}

func (*ClientSignal_UnsubscribeRequest) isClientSignal_Payload() {}

func (*ClientSignal_UnsubscribeResponse) isClientSignal_Payload() {}

func (*ClientSignal_MessageAck) isClientSignal_Payload() {}

func (*ClientSignal_BusinessUp) isClientSignal_Payload() {}

func (*ClientSignal_BusinessDown) isClientSignal_Payload() {}

// 客户端按服务端指定的间隔发送心跳，维持连接存活
type HeartbeatPing struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp uint64                 `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"` // 客户端发送时间戳（毫秒），用于延迟计算
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatPing) GetClientTimestamp() uint64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

// 服务端响应心跳，返回客户端的延迟时间
type HeartbeatPong struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestamp uint64                 `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"` // 服务端响应时间戳（毫秒）
	ClientTimestamp uint64                 `protobuf:"varint,2,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"` // 回传客户端发送时间戳（毫秒），用于客户端校准
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatPong) GetServerTimestamp() uint64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *HeartbeatPong) GetClientTimestamp() uint64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

// Auth 鉴权，连接建立后，客户端必须在5s内发起鉴权，未鉴权连接禁止收发业务信息，超时直接关闭
type AuthRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                         // 业务侧签发的鉴权token，网关校验合法性
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                         // 业务侧唯一标识
	DeviceId          string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                   // 设备ID
	Platform          string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                                                   // 客户端平台，如 web、iOS、Android等
	ClientVersion     *string                `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3,oneof" json:"client_version,omitempty"`              // 客户端版本号，用于兼容升级
	HeartbeatInterval *uint32                `protobuf:"varint,6,opt,name=heartbeat_interval,json=heartbeatInterval,proto3,oneof" json:"heartbeat_interval,omitempty"` // 客户端期望的心跳间隔（单位秒），最终以服务端返回的为准
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_v1_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AuthRequest) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *AuthRequest) GetHeartbeatInterval() uint32 {
	if x != nil && x.HeartbeatInterval != nil {
		return *x.HeartbeatInterval
	}
	return 0
}

type AuthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                       // 响应，0 = 鉴权成功，非0 失败
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                                          // 状态描述
	Result            bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`                                                   // 鉴权结果，true = 鉴权成功，false = 鉴权失败
	HeartbeatInternal uint32                 `protobuf:"varint,4,opt,name=heartbeat_internal,json=heartbeatInternal,proto3" json:"heartbeat_internal,omitempty"`    // 服务端强制的心跳间隔（单位秒，默认 30s）
	ConnectionExpire  *uint64                `protobuf:"varint,5,opt,name=connection_expire,json=connectionExpire,proto3,oneof" json:"connection_expire,omitempty"` // 连接过期时间戳（单位秒），连接在该时间后自动断开
	MaxPacketSize     *uint32                `protobuf:"varint,6,opt,name=max_packet_size,json=maxPacketSize,proto3,oneof" json:"max_packet_size,omitempty"`        // 服务端支持的最大数据包大小（字节），超过该大小的数据包将被拒绝
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_v1_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *AuthResponse) GetHeartbeatInternal() uint32 {
	if x != nil {
		return x.HeartbeatInternal
	}
	return 0
}

func (x *AuthResponse) GetConnectionExpire() uint64 {
	if x != nil && x.ConnectionExpire != nil {
		return *x.ConnectionExpire
	}
	return 0
}

func (x *AuthResponse) GetMaxPacketSize() uint32 {
	if x != nil && x.MaxPacketSize != nil {
		return *x.MaxPacketSize
	}
	return 0
}

// 客户端收到 Qos >= 1 的下行消息后，向网关上报ACK，完成可靠投递，网关收到 ACK 后，停止重试
type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckMsgId      []string               `protobuf:"bytes,1,rep,name=ack_msg_id,json=ackMsgId,proto3" json:"ack_msg_id,omitempty"`                                                                            // 已收到的消息ID列表，支持批量ACK减少流量
	AckResult     map[string]string      `protobuf:"bytes,2,rep,name=ack_result,json=ackResult,proto3" json:"ack_result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 已收到的消息ID及其处理结果，true = 处理成功，false = 处理失败
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_v1_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{5}
}

func (x *MessageAck) GetAckMsgId() []string {
	if x != nil {
		return x.AckMsgId
	}
	return nil
}

func (x *MessageAck) GetAckResult() map[string]string {
	if x != nil {
		return x.AckResult
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        uint32                 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` // 登出原因，1 = 用户主动登出，2 = 切换账号，3 = 其他
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_v1_signal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应，0 = 登出成功，非0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_v1_signal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LogoutResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 主题订阅 / 取消订阅接口；这些需要业务侧进行处理，记录每个 userId 订阅了哪些 topic；todo ，这里后面需要好好设计一下
// 适用场景：群聊、直播间、行情推送等 Pub/Sub 场景，客户端订阅主题后，网关自动转发该主题的消息。
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // 订阅的主题
	Qos           uint32                 `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`    // 订阅质量等级，0 = 至多一次，1 = 至少一次，2 = 只有一次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_v1_signal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应，0 = 订阅成功，非0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_v1_signal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubscribeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // 取消订阅的主题
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_v1_signal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{10}
}

func (x *UnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应，0 = 取消订阅成功，非0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_v1_signal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{11}
}

func (x *UnsubscribeResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnsubscribeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BusinessUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                // 业务消息唯一ID
	Type          BusinessType           `protobuf:"varint,2,opt,name=type,proto3,enum=gateway.v1.BusinessType" json:"type,omitempty"` // 业务消息类型
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                               // 业务消息体，网关不解析，直接透传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessUp) Reset() {
	*x = BusinessUp{}
	mi := &file_v1_signal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessUp) ProtoMessage() {}

func (x *BusinessUp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessUp.ProtoReflect.Descriptor instead.
func (*BusinessUp) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{12}
}

func (x *BusinessUp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *BusinessUp) GetType() BusinessType {
	if x != nil {
		return x.Type
	}
	return BusinessType_BusinessType_UNSPECIFIED
}

func (x *BusinessUp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type BusinessDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                // 业务消息唯一ID
	Type          BusinessType           `protobuf:"varint,2,opt,name=type,proto3,enum=gateway.v1.BusinessType" json:"type,omitempty"` // 业务消息类型
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                               // 业务消息体，网关不解析，直接透传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessDown) Reset() {
	*x = BusinessDown{}
	mi := &file_v1_signal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessDown) ProtoMessage() {}

func (x *BusinessDown) ProtoReflect() protoreflect.Message {
	mi := &file_v1_signal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessDown.ProtoReflect.Descriptor instead.
func (*BusinessDown) Descriptor() ([]byte, []int) {
	return file_v1_signal_proto_rawDescGZIP(), []int{13}
}

func (x *BusinessDown) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *BusinessDown) GetType() BusinessType {
	if x != nil {
		return x.Type
	}
	return BusinessType_BusinessType_UNSPECIFIED
}

func (x *BusinessDown) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_v1_signal_proto protoreflect.FileDescriptor

const file_v1_signal_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/signal.proto\x12\n" +
	"gateway.v1\x1a\x10v1/gateway.proto\"\xa1\b\n" +
	"\fClientSignal\x127\n" +
	"\vsignal_type\x18\x01 \x01(\x0e2\x16.gateway.v1.SignalTypeR\n" +
	"signalType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vsequence_id\x18\x03 \x01(\x04R\n" +
	"sequenceId\x12B\n" +
	"\x0eheartbeat_ping\x18\n" +
	" \x01(\v2\x19.gateway.v1.HeartbeatPingH\x00R\rheartbeatPing\x12B\n" +
	"\x0eheartbeat_pong\x18\v \x01(\v2\x19.gateway.v1.HeartbeatPongH\x00R\rheartbeatPong\x12<\n" +
	"\fauth_request\x18\f \x01(\v2\x17.gateway.v1.AuthRequestH\x00R\vauthRequest\x12?\n" +
	"\rauth_response\x18\r \x01(\v2\x18.gateway.v1.AuthResponseH\x00R\fauthResponse\x12B\n" +
	"\x0elogout_request\x18\x0e \x01(\v2\x19.gateway.v1.LogoutRequestH\x00R\rlogoutRequest\x12E\n" +
	"\x0flogout_response\x18\x0f \x01(\v2\x1a.gateway.v1.LogoutResponseH\x00R\x0elogoutResponse\x12K\n" +
	"\x11subscribe_request\x18\x10 \x01(\v2\x1c.gateway.v1.SubscribeRequestH\x00R\x10subscribeRequest\x12N\n" +
	"\x12subscribe_response\x18\x11 \x01(\v2\x1d.gateway.v1.SubscribeResponseH\x00R\x11subscribeResponse\x12Q\n" +
	"\x13unsubscribe_request\x18\x12 \x01(\v2\x1e.gateway.v1.UnsubscribeRequestH\x00R\x12unsubscribeRequest\x12T\n" +
	"\x14unsubscribe_response\x18\x13 \x01(\v2\x1f.gateway.v1.UnsubscribeResponseH\x00R\x13unsubscribeResponse\x129\n" +
	"\vmessage_ack\x18c \x01(\v2\x16.gateway.v1.MessageAckH\x00R\n" +
	"messageAck\x129\n" +
	"\vbusiness_up\x18d \x01(\v2\x16.gateway.v1.BusinessUpH\x00R\n" +
	"businessUp\x12?\n" +
	"\rbusiness_down\x18e \x01(\v2\x18.gateway.v1.BusinessDownH\x00R\fbusinessDownB\t\n" +
	"\apayload\":\n" +
	"\rHeartbeatPing\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x04R\x0fclientTimestamp\"e\n" +
	"\rHeartbeatPong\x12)\n" +
	"\x10server_timestamp\x18\x01 \x01(\x04R\x0fserverTimestamp\x12)\n" +
	"\x10client_timestamp\x18\x02 \x01(\x04R\x0fclientTimestamp\"\xff\x01\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12*\n" +
	"\x0eclient_version\x18\x05 \x01(\tH\x00R\rclientVersion\x88\x01\x01\x122\n" +
	"\x12heartbeat_interval\x18\x06 \x01(\rH\x01R\x11heartbeatInterval\x88\x01\x01B\x11\n" +
	"\x0f_client_versionB\x15\n" +
	"\x13_heartbeat_interval\"\x84\x02\n" +
	"\fAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x12-\n" +
	"\x12heartbeat_internal\x18\x04 \x01(\rR\x11heartbeatInternal\x120\n" +
	"\x11connection_expire\x18\x05 \x01(\x04H\x00R\x10connectionExpire\x88\x01\x01\x12+\n" +
	"\x0fmax_packet_size\x18\x06 \x01(\rH\x01R\rmaxPacketSize\x88\x01\x01B\x14\n" +
	"\x12_connection_expireB\x12\n" +
	"\x10_max_packet_size\"\xae\x01\n" +
	"\n" +
	"MessageAck\x12\x1c\n" +
	"\n" +
	"ack_msg_id\x18\x01 \x03(\tR\backMsgId\x12D\n" +
	"\n" +
	"ack_result\x18\x02 \x03(\v2%.gateway.v1.MessageAck.AckResultEntryR\tackResult\x1a<\n" +
	"\x0eAckResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\rLogoutRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\rR\x06reason\"6\n" +
	"\x0eLogoutResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\":\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03qos\x18\x02 \x01(\rR\x03qos\"9\n" +
	"\x11SubscribeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"*\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\";\n" +
	"\x13UnsubscribeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"e\n" +
	"\n" +
	"BusinessUp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.gateway.v1.BusinessTypeR\x04type\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"g\n" +
	"\fBusinessDown\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.gateway.v1.BusinessTypeR\x04type\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body*\xd2\x03\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSIGNAL_TYPE_HEARTBEAT_PING\x10\x01\x12\x1e\n" +
	"\x1aSIGNAL_TYPE_HEARTBEAT_PONG\x10\x02\x12\x1c\n" +
	"\x18SIGNAL_TYPE_AUTH_REQUEST\x10\x03\x12\x1d\n" +
	"\x19SIGNAL_TYPE_AUTH_RESPONSE\x10\x04\x12\x1b\n" +
	"\x17SIGNAL_TYPE_MESSAGE_ACK\x10\x05\x12\x1e\n" +
	"\x1aSIGNAL_TYPE_LOGOUT_REQUEST\x10\a\x12\x1f\n" +
	"\x1bSIGNAL_TYPE_LOGOUT_RESPONSE\x10\b\x12!\n" +
	"\x1dSIGNAL_TYPE_SUBSCRIBE_REQUEST\x10\t\x12\"\n" +
	"\x1eSIGNAL_TYPE_SUBSCRIBE_RESPONSE\x10\n" +
	"\x12#\n" +
	"\x1fSIGNAL_TYPE_UNSUBSCRIBE_REQUEST\x10\v\x12$\n" +
	" SIGNAL_TYPE_UNSUBSCRIBE_RESPONSE\x10\f\x12\x1b\n" +
	"\x17SIGNAL_TYPE_BUSINESS_UP\x10d\x12\x1d\n" +
	"\x19SIGNAL_TYPE_BUSINESS_DOWN\x10eB0Z.github.com/vadam-zhan/long-gw/proto/v1;gatewayb\x06proto3"

var (
	file_v1_signal_proto_rawDescOnce sync.Once
	file_v1_signal_proto_rawDescData []byte
)

func file_v1_signal_proto_rawDescGZIP() []byte {
	file_v1_signal_proto_rawDescOnce.Do(func() {
		file_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_signal_proto_rawDesc), len(file_v1_signal_proto_rawDesc)))
	})
	return file_v1_signal_proto_rawDescData
}

var file_v1_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_signal_proto_goTypes = []any{
	(SignalType)(0),             // 0: gateway.v1.SignalType
	(*ClientSignal)(nil),        // 1: gateway.v1.ClientSignal
	(*HeartbeatPing)(nil),       // 2: gateway.v1.HeartbeatPing
	(*HeartbeatPong)(nil),       // 3: gateway.v1.HeartbeatPong
	(*AuthRequest)(nil),         // 4: gateway.v1.AuthRequest
	(*AuthResponse)(nil),        // 5: gateway.v1.AuthResponse
	(*MessageAck)(nil),          // 6: gateway.v1.MessageAck
	(*LogoutRequest)(nil),       // 7: gateway.v1.LogoutRequest
	(*LogoutResponse)(nil),      // 8: gateway.v1.LogoutResponse
	(*SubscribeRequest)(nil),    // 9: gateway.v1.SubscribeRequest
	(*SubscribeResponse)(nil),   // 10: gateway.v1.SubscribeResponse
	(*UnsubscribeRequest)(nil),  // 11: gateway.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 12: gateway.v1.UnsubscribeResponse
	(*BusinessUp)(nil),          // 13: gateway.v1.BusinessUp
	(*BusinessDown)(nil),        // 14: gateway.v1.BusinessDown
	nil,                         // 15: gateway.v1.MessageAck.AckResultEntry
	(BusinessType)(0),           // 16: gateway.v1.BusinessType
}
var file_v1_signal_proto_depIdxs = []int32{
	0,  // 0: gateway.v1.ClientSignal.signal_type:type_name -> gateway.v1.SignalType
	2,  // 1: gateway.v1.ClientSignal.heartbeat_ping:type_name -> gateway.v1.HeartbeatPing
	3,  // 2: gateway.v1.ClientSignal.heartbeat_pong:type_name -> gateway.v1.HeartbeatPong
	4,  // 3: gateway.v1.ClientSignal.auth_request:type_name -> gateway.v1.AuthRequest
	5,  // 4: gateway.v1.ClientSignal.auth_response:type_name -> gateway.v1.AuthResponse
	7,  // 5: gateway.v1.ClientSignal.logout_request:type_name -> gateway.v1.LogoutRequest
	8,  // 6: gateway.v1.ClientSignal.logout_response:type_name -> gateway.v1.LogoutResponse
	9,  // 7: gateway.v1.ClientSignal.subscribe_request:type_name -> gateway.v1.SubscribeRequest
	10, // 8: gateway.v1.ClientSignal.subscribe_response:type_name -> gateway.v1.SubscribeResponse
	11, // 9: gateway.v1.ClientSignal.unsubscribe_request:type_name -> gateway.v1.UnsubscribeRequest
	12, // 10: gateway.v1.ClientSignal.unsubscribe_response:type_name -> gateway.v1.UnsubscribeResponse
	6,  // 11: gateway.v1.ClientSignal.message_ack:type_name -> gateway.v1.MessageAck
	13, // 12: gateway.v1.ClientSignal.business_up:type_name -> gateway.v1.BusinessUp
	14, // 13: gateway.v1.ClientSignal.business_down:type_name -> gateway.v1.BusinessDown
	15, // 14: gateway.v1.MessageAck.ack_result:type_name -> gateway.v1.MessageAck.AckResultEntry
	16, // 15: gateway.v1.BusinessUp.type:type_name -> gateway.v1.BusinessType
	16, // 16: gateway.v1.BusinessDown.type:type_name -> gateway.v1.BusinessType
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_v1_signal_proto_init() }
func file_v1_signal_proto_init() {
	if File_v1_signal_proto != nil {
		return
	}
	file_v1_gateway_proto_init()
	file_v1_signal_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientSignal_HeartbeatPing)(nil),
		(*ClientSignal_HeartbeatPong)(nil),
		(*ClientSignal_AuthRequest)(nil),
		(*ClientSignal_AuthResponse)(nil),
		(*ClientSignal_LogoutRequest)(nil),
		(*ClientSignal_LogoutResponse)(nil),
		(*ClientSignal_SubscribeRequest)(nil),
		(*ClientSignal_SubscribeResponse)(nil),
		(*ClientSignal_UnsubscribeRequest)(nil),
		(*ClientSignal_UnsubscribeResponse)(nil),
		(*ClientSignal_MessageAck)(nil),
		(*ClientSignal_BusinessUp)(nil),
		(*ClientSignal_BusinessDown)(nil),
	}
	file_v1_signal_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_signal_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_signal_proto_rawDesc), len(file_v1_signal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_signal_proto_goTypes,
		DependencyIndexes: file_v1_signal_proto_depIdxs,
		EnumInfos:         file_v1_signal_proto_enumTypes,
		MessageInfos:      file_v1_signal_proto_msgTypes,
	}.Build()
	File_v1_signal_proto = out.File
	file_v1_signal_proto_goTypes = nil
	file_v1_signal_proto_depIdxs = nil
}
