gateway:
  addr: ":8089"
  read_buf_size: 4096
  write_buf_size: 4096
  upstream_worker_num: 50
  downstream_worker_num: 50
  max_conn_num: 1000000
  profile:
    enabled: false
    addr: ":8088"
  metrics:
    enabled: true
    addr: ":9091"

redis:
  # addr: "host.docker.internal:6379"
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 100
  route_ttl: 120

# 上行配置（Gateway -> Backend）
upstream:
  kind: "kafka" # kafka 或 grpc
  kafka:
    brokers:
      # - "host.docker.internal:9092"
      # - "kafka:29092"
      - "localhost:9092"
    business_topics:
      im:
        upstream: "gw.im.up"
        dlq: "gw.im.up.DLQ"
        downstream: "gw.im.down"
      live:
        upstream: "gw.live.up"
        dlq: "gw.live.up.DLQ"
        downstream: "gw.live.down"
      message:
        upstream: "gw.message.up"
        dlq: "gw.message.up.DLQ"
        downstream: "gw.message.down"
  grpc:
    business_config:
      im:
        grpc_addr: "localhost:8090"
      live:
        grpc_addr: "localhost:8091"

auth:
  addr: "localhost:8081"

log:
  level: "info"
  format: "json"
  file: ""

# 数据库配置（用于离线消息存储）
database:
  dsn: "root:password@tcp(localhost:3306)/gateway?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_life: 3600
