// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 多个业务方: IM、直播、消息中心等，用于管理多个业务方的 worker 池
type BusinessType int32

const (
	BusinessType_UNSPECIFIED BusinessType = 0
	BusinessType_IM          BusinessType = 1 // IM 业务
	BusinessType_LIVE        BusinessType = 2 // 直播业务
	BusinessType_MESSAGE     BusinessType = 3 // 消息中心业务
)

// Enum value maps for BusinessType.
var (
	BusinessType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "IM",
		2: "LIVE",
		3: "MESSAGE",
	}
	BusinessType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"IM":          1,
		"LIVE":        2,
		"MESSAGE":     3,
	}
)

func (x BusinessType) Enum() *BusinessType {
	p := new(BusinessType)
	*p = x
	return p
}

func (x BusinessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (BusinessType) Type() protoreflect.EnumType {
	return &file_v1_gateway_proto_enumTypes[0]
}

func (x BusinessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessType.Descriptor instead.
func (BusinessType) EnumDescriptor() ([]byte, []int) {
	return file_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type PushMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                                                           // 接收者 ID
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                                             // 业务载荷
	BusinessType  BusinessType           `protobuf:"varint,4,opt,name=business_type,json=businessType,proto3,enum=gateway.v1.BusinessType" json:"business_type,omitempty"` // 业务类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageReq) Reset() {
	*x = PushMessageReq{}
	mi := &file_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageReq) ProtoMessage() {}

func (x *PushMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageReq.ProtoReflect.Descriptor instead.
func (*PushMessageReq) Descriptor() ([]byte, []int) {
	return file_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *PushMessageReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushMessageReq) GetBusinessType() BusinessType {
	if x != nil {
		return x.BusinessType
	}
	return BusinessType_UNSPECIFIED
}

type PushMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageResp) Reset() {
	*x = PushMessageResp{}
	mi := &file_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResp) ProtoMessage() {}

func (x *PushMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResp.ProtoReflect.Descriptor instead.
func (*PushMessageResp) Descriptor() ([]byte, []int) {
	return file_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMessageResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_gateway_proto protoreflect.FileDescriptor

const file_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x10v1/gateway.proto\x12\n" +
	"gateway.v1\"\x85\x01\n" +
	"\x0ePushMessageReq\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12=\n" +
	"\rbusiness_type\x18\x04 \x01(\x0e2\x18.gateway.v1.BusinessTypeR\fbusinessType\"E\n" +
	"\x0fPushMessageResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*>\n" +
	"\fBusinessType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02IM\x10\x01\x12\b\n" +
	"\x04LIVE\x10\x02\x12\v\n" +
	"\aMESSAGE\x10\x032Q\n" +
	"\aGateway\x12F\n" +
	"\vPushMessage\x12\x1a.gateway.v1.PushMessageReq\x1a\x1b.gateway.v1.PushMessageRespB0Z.github.com/vadam-zhan/long-gw/proto/v1;gatewayb\x06proto3"

var (
	file_v1_gateway_proto_rawDescOnce sync.Once
	file_v1_gateway_proto_rawDescData []byte
)

func file_v1_gateway_proto_rawDescGZIP() []byte {
	file_v1_gateway_proto_rawDescOnce.Do(func() {
		file_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_gateway_proto_rawDesc), len(file_v1_gateway_proto_rawDesc)))
	})
	return file_v1_gateway_proto_rawDescData
}

var file_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_gateway_proto_goTypes = []any{
	(BusinessType)(0),       // 0: gateway.v1.BusinessType
	(*PushMessageReq)(nil),  // 1: gateway.v1.PushMessageReq
	(*PushMessageResp)(nil), // 2: gateway.v1.PushMessageResp
}
var file_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.v1.PushMessageReq.business_type:type_name -> gateway.v1.BusinessType
	1, // 1: gateway.v1.Gateway.PushMessage:input_type -> gateway.v1.PushMessageReq
	2, // 2: gateway.v1.Gateway.PushMessage:output_type -> gateway.v1.PushMessageResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_gateway_proto_init() }
func file_v1_gateway_proto_init() {
	if File_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_gateway_proto_rawDesc), len(file_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_gateway_proto_goTypes,
		DependencyIndexes: file_v1_gateway_proto_depIdxs,
		EnumInfos:         file_v1_gateway_proto_enumTypes,
		MessageInfos:      file_v1_gateway_proto_msgTypes,
	}.Build()
	File_v1_gateway_proto = out.File
	file_v1_gateway_proto_goTypes = nil
	file_v1_gateway_proto_depIdxs = nil
}
