// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/kafka_message.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KafkaMessageType defines the direction and purpose of Kafka messages
type KafkaMessageType int32

const (
	KafkaMessageType_KAFKA_MSG_UNSPECIFIED KafkaMessageType = 0
	// Upstream: gateway -> backend (client message forwarded)
	KafkaMessageType_KAFKA_MSG_UPSTREAM KafkaMessageType = 1
	// Downstream: backend -> gateway (response to be delivered to client)
	KafkaMessageType_KAFKA_MSG_DOWNSTREAM KafkaMessageType = 2
)

// Enum value maps for KafkaMessageType.
var (
	KafkaMessageType_name = map[int32]string{
		0: "KAFKA_MSG_UNSPECIFIED",
		1: "KAFKA_MSG_UPSTREAM",
		2: "KAFKA_MSG_DOWNSTREAM",
	}
	KafkaMessageType_value = map[string]int32{
		"KAFKA_MSG_UNSPECIFIED": 0,
		"KAFKA_MSG_UPSTREAM":    1,
		"KAFKA_MSG_DOWNSTREAM":  2,
	}
)

func (x KafkaMessageType) Enum() *KafkaMessageType {
	p := new(KafkaMessageType)
	*p = x
	return p
}

func (x KafkaMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KafkaMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_kafka_message_proto_enumTypes[0].Descriptor()
}

func (KafkaMessageType) Type() protoreflect.EnumType {
	return &file_v1_kafka_message_proto_enumTypes[0]
}

func (x KafkaMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KafkaMessageType.Descriptor instead.
func (KafkaMessageType) EnumDescriptor() ([]byte, []int) {
	return file_v1_kafka_message_proto_rawDescGZIP(), []int{0}
}

// UpstreamKafkaMessage is sent from gateway to backend
type UpstreamKafkaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                            // UUID for request/response matching
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`                                                 // Connection identifier (for routing back)
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                 // Client user ID
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                           // Client device ID
	OriginalType  SignalType             `protobuf:"varint,5,opt,name=original_type,json=originalType,proto3,enum=gateway.v1.SignalType" json:"original_type,omitempty"`   // Original client message type
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                                             // Original message body
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                        // Unix timestamp (ms)
	BusinessType  BusinessType           `protobuf:"varint,8,opt,name=business_type,json=businessType,proto3,enum=gateway.v1.BusinessType" json:"business_type,omitempty"` // 消息属于哪个业务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamKafkaMessage) Reset() {
	*x = UpstreamKafkaMessage{}
	mi := &file_v1_kafka_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamKafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamKafkaMessage) ProtoMessage() {}

func (x *UpstreamKafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kafka_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamKafkaMessage.ProtoReflect.Descriptor instead.
func (*UpstreamKafkaMessage) Descriptor() ([]byte, []int) {
	return file_v1_kafka_message_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamKafkaMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *UpstreamKafkaMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *UpstreamKafkaMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpstreamKafkaMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpstreamKafkaMessage) GetOriginalType() SignalType {
	if x != nil {
		return x.OriginalType
	}
	return SignalType_Signal_Type_UNSPECIFIED
}

func (x *UpstreamKafkaMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpstreamKafkaMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpstreamKafkaMessage) GetBusinessType() BusinessType {
	if x != nil {
		return x.BusinessType
	}
	return BusinessType_BusinessType_UNSPECIFIED
}

// DownstreamKafkaMessage is sent from backend to gateway
type DownstreamKafkaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                            // Matches the upstream correlation_id
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`                                                 // Target connection (gateway uses to route)
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                 // Target user ID (for validation)
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                           // Target device ID (for validation)
	TargetType    SignalType             `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=gateway.v1.SignalType" json:"target_type,omitempty"`         // Message type to send to client
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                                             // Response body for client
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                        // Unix timestamp (ms)
	BusinessType  BusinessType           `protobuf:"varint,8,opt,name=business_type,json=businessType,proto3,enum=gateway.v1.BusinessType" json:"business_type,omitempty"` // 消息属于哪个业务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownstreamKafkaMessage) Reset() {
	*x = DownstreamKafkaMessage{}
	mi := &file_v1_kafka_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownstreamKafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamKafkaMessage) ProtoMessage() {}

func (x *DownstreamKafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kafka_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamKafkaMessage.ProtoReflect.Descriptor instead.
func (*DownstreamKafkaMessage) Descriptor() ([]byte, []int) {
	return file_v1_kafka_message_proto_rawDescGZIP(), []int{1}
}

func (x *DownstreamKafkaMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DownstreamKafkaMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *DownstreamKafkaMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DownstreamKafkaMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DownstreamKafkaMessage) GetTargetType() SignalType {
	if x != nil {
		return x.TargetType
	}
	return SignalType_Signal_Type_UNSPECIFIED
}

func (x *DownstreamKafkaMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownstreamKafkaMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DownstreamKafkaMessage) GetBusinessType() BusinessType {
	if x != nil {
		return x.BusinessType
	}
	return BusinessType_BusinessType_UNSPECIFIED
}

var File_v1_kafka_message_proto protoreflect.FileDescriptor

const file_v1_kafka_message_proto_rawDesc = "" +
	"\n" +
	"\x16v1/kafka_message.proto\x12\n" +
	"gateway.v1\x1a\x10v1/gateway.proto\x1a\x10v1/message.proto\"\xc0\x02\n" +
	"\x14UpstreamKafkaMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12;\n" +
	"\roriginal_type\x18\x05 \x01(\x0e2\x16.gateway.v1.SignalTypeR\foriginalType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12=\n" +
	"\rbusiness_type\x18\b \x01(\x0e2\x18.gateway.v1.BusinessTypeR\fbusinessType\"\xbe\x02\n" +
	"\x16DownstreamKafkaMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x127\n" +
	"\vtarget_type\x18\x05 \x01(\x0e2\x16.gateway.v1.SignalTypeR\n" +
	"targetType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12=\n" +
	"\rbusiness_type\x18\b \x01(\x0e2\x18.gateway.v1.BusinessTypeR\fbusinessType*_\n" +
	"\x10KafkaMessageType\x12\x19\n" +
	"\x15KAFKA_MSG_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KAFKA_MSG_UPSTREAM\x10\x01\x12\x18\n" +
	"\x14KAFKA_MSG_DOWNSTREAM\x10\x02B0Z.github.com/vadam-zhan/long-gw/proto/v1;gatewayb\x06proto3"

var (
	file_v1_kafka_message_proto_rawDescOnce sync.Once
	file_v1_kafka_message_proto_rawDescData []byte
)

func file_v1_kafka_message_proto_rawDescGZIP() []byte {
	file_v1_kafka_message_proto_rawDescOnce.Do(func() {
		file_v1_kafka_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_kafka_message_proto_rawDesc), len(file_v1_kafka_message_proto_rawDesc)))
	})
	return file_v1_kafka_message_proto_rawDescData
}

var file_v1_kafka_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_kafka_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_kafka_message_proto_goTypes = []any{
	(KafkaMessageType)(0),          // 0: gateway.v1.KafkaMessageType
	(*UpstreamKafkaMessage)(nil),   // 1: gateway.v1.UpstreamKafkaMessage
	(*DownstreamKafkaMessage)(nil), // 2: gateway.v1.DownstreamKafkaMessage
	(SignalType)(0),                // 3: gateway.v1.SignalType
	(BusinessType)(0),              // 4: gateway.v1.BusinessType
}
var file_v1_kafka_message_proto_depIdxs = []int32{
	3, // 0: gateway.v1.UpstreamKafkaMessage.original_type:type_name -> gateway.v1.SignalType
	4, // 1: gateway.v1.UpstreamKafkaMessage.business_type:type_name -> gateway.v1.BusinessType
	3, // 2: gateway.v1.DownstreamKafkaMessage.target_type:type_name -> gateway.v1.SignalType
	4, // 3: gateway.v1.DownstreamKafkaMessage.business_type:type_name -> gateway.v1.BusinessType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_kafka_message_proto_init() }
func file_v1_kafka_message_proto_init() {
	if File_v1_kafka_message_proto != nil {
		return
	}
	file_v1_gateway_proto_init()
	file_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_kafka_message_proto_rawDesc), len(file_v1_kafka_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_kafka_message_proto_goTypes,
		DependencyIndexes: file_v1_kafka_message_proto_depIdxs,
		EnumInfos:         file_v1_kafka_message_proto_enumTypes,
		MessageInfos:      file_v1_kafka_message_proto_msgTypes,
	}.Build()
	File_v1_kafka_message_proto = out.File
	file_v1_kafka_message_proto_goTypes = nil
	file_v1_kafka_message_proto_depIdxs = nil
}
