// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/message.proto

package gateway

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_Signal_Type_UNSPECIFIED SignalType = 0
	// ── 控制面 (1–99) ── 网关内部，不转发给业务 ──────────────────────────────
	SignalType_Signal_Type_HANDSHAKE     SignalType = 1 // Client→Gateway  初始认证握手
	SignalType_Signal_Type_HANDSHAKE_ACK SignalType = 2 // Gateway→Client  握手结果
	SignalType_Signal_Type_PING          SignalType = 3 // Client→Gateway  心跳探针
	SignalType_Signal_Type_PONG          SignalType = 4 // Gateway→Client  心跳回应
	SignalType_Signal_Type_KICK          SignalType = 5 // Gateway→Client  强制断连通知
	SignalType_Signal_Type_ERROR         SignalType = 6 // 双向             错误通知
	SignalType_Signal_Type_ACK           SignalType = 7 // 双向             QoS-1/2 确认帧
	// ── 数据面通用 (100) ─────────────────────────────────────────────────────
	SignalType_Signal_Type_DATA SignalType = 100 // 通用数据帧，BizCode+Body.type 细分路由
	// ── IM 域 (101–199) ──────────────────────────────────────────────────────
	SignalType_Signal_Type_IM_CHAT    SignalType = 101 // 单聊 / 群聊消息
	SignalType_Signal_Type_IM_RECEIPT SignalType = 102 // 投递 / 已读回执
	SignalType_Signal_Type_IM_REVOKE  SignalType = 103 // 消息撤回
	SignalType_Signal_Type_IM_TYPING  SignalType = 104 // 正在输入指示
	// ── Push 域 (201–299) ────────────────────────────────────────────────────
	SignalType_Signal_Type_PUSH_NOTIFY SignalType = 201 // 服务端主动推送
	SignalType_Signal_Type_PUSH_ACK    SignalType = 202 // 客户端推送确认
	// ── Live 域 (301–399) ────────────────────────────────────────────────────
	SignalType_Signal_Type_LIVE_JOIN    SignalType = 301
	SignalType_Signal_Type_LIVE_LEAVE   SignalType = 302
	SignalType_Signal_Type_LIVE_COMMENT SignalType = 303
	SignalType_Signal_Type_LIVE_GIFT    SignalType = 304
	SignalType_Signal_Type_LIVE_SIGNAL  SignalType = 305
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0:   "Signal_Type_UNSPECIFIED",
		1:   "Signal_Type_HANDSHAKE",
		2:   "Signal_Type_HANDSHAKE_ACK",
		3:   "Signal_Type_PING",
		4:   "Signal_Type_PONG",
		5:   "Signal_Type_KICK",
		6:   "Signal_Type_ERROR",
		7:   "Signal_Type_ACK",
		100: "Signal_Type_DATA",
		101: "Signal_Type_IM_CHAT",
		102: "Signal_Type_IM_RECEIPT",
		103: "Signal_Type_IM_REVOKE",
		104: "Signal_Type_IM_TYPING",
		201: "Signal_Type_PUSH_NOTIFY",
		202: "Signal_Type_PUSH_ACK",
		301: "Signal_Type_LIVE_JOIN",
		302: "Signal_Type_LIVE_LEAVE",
		303: "Signal_Type_LIVE_COMMENT",
		304: "Signal_Type_LIVE_GIFT",
		305: "Signal_Type_LIVE_SIGNAL",
	}
	SignalType_value = map[string]int32{
		"Signal_Type_UNSPECIFIED":   0,
		"Signal_Type_HANDSHAKE":     1,
		"Signal_Type_HANDSHAKE_ACK": 2,
		"Signal_Type_PING":          3,
		"Signal_Type_PONG":          4,
		"Signal_Type_KICK":          5,
		"Signal_Type_ERROR":         6,
		"Signal_Type_ACK":           7,
		"Signal_Type_DATA":          100,
		"Signal_Type_IM_CHAT":       101,
		"Signal_Type_IM_RECEIPT":    102,
		"Signal_Type_IM_REVOKE":     103,
		"Signal_Type_IM_TYPING":     104,
		"Signal_Type_PUSH_NOTIFY":   201,
		"Signal_Type_PUSH_ACK":      202,
		"Signal_Type_LIVE_JOIN":     301,
		"Signal_Type_LIVE_LEAVE":    302,
		"Signal_Type_LIVE_COMMENT":  303,
		"Signal_Type_LIVE_GIFT":     304,
		"Signal_Type_LIVE_SIGNAL":   305,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_message_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_v1_message_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{0}
}

// QoS 投递保证等级，语义对齐 MQTT
type QoS int32

const (
	QoS_QOS_AT_MOST_ONCE  QoS = 0 // 最多一次：发完即忘，无 ACK（弹幕、位置）
	QoS_QOS_AT_LEAST_ONCE QoS = 1 // 至少一次：SDK 重试直到收到 ACK，可能重复（IM）
	QoS_QOS_EXACTLY_ONCE  QoS = 2 // 恰好一次：接收端去重（金融事件）
)

// Enum value maps for QoS.
var (
	QoS_name = map[int32]string{
		0: "QOS_AT_MOST_ONCE",
		1: "QOS_AT_LEAST_ONCE",
		2: "QOS_EXACTLY_ONCE",
	}
	QoS_value = map[string]int32{
		"QOS_AT_MOST_ONCE":  0,
		"QOS_AT_LEAST_ONCE": 1,
		"QOS_EXACTLY_ONCE":  2,
	}
)

func (x QoS) Enum() *QoS {
	p := new(QoS)
	*p = x
	return p
}

func (x QoS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QoS) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_message_proto_enumTypes[1].Descriptor()
}

func (QoS) Type() protoreflect.EnumType {
	return &file_v1_message_proto_enumTypes[1]
}

func (x QoS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QoS.Descriptor instead.
func (QoS) EnumDescriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{1}
}

// Codec 编码格式：作用于 Body.payload 字节的序列化方式
type Codec int32

const (
	Codec_Codec_UNSPECIFIED Codec = 0 // 由实现自行约定（历史兼容）
	Codec_Codec_JSON        Codec = 1 // 调试友好，默认
	Codec_Codec_PROTOBUF    Codec = 2 // 生产首选，紧凑高效
	Codec_Codec_MSGPACK     Codec = 3 // 动态语言场景
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "Codec_UNSPECIFIED",
		1: "Codec_JSON",
		2: "Codec_PROTOBUF",
		3: "Codec_MSGPACK",
	}
	Codec_value = map[string]int32{
		"Codec_UNSPECIFIED": 0,
		"Codec_JSON":        1,
		"Codec_PROTOBUF":    2,
		"Codec_MSGPACK":     3,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_message_proto_enumTypes[2].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_v1_message_proto_enumTypes[2]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{2}
}

// CompressAlgo 压缩算法：作用于编码后的 payload 字节
type CompressAlgo int32

const (
	CompressAlgo_Compress_Algo_NONE   CompressAlgo = 0
	CompressAlgo_Compress_Algo_GZIP   CompressAlgo = 1
	CompressAlgo_Compress_Algo_ZSTD   CompressAlgo = 2 // 推荐：压缩比与速度最优
	CompressAlgo_Compress_Algo_SNAPPY CompressAlgo = 3 // 低延迟场景
)

// Enum value maps for CompressAlgo.
var (
	CompressAlgo_name = map[int32]string{
		0: "Compress_Algo_NONE",
		1: "Compress_Algo_GZIP",
		2: "Compress_Algo_ZSTD",
		3: "Compress_Algo_SNAPPY",
	}
	CompressAlgo_value = map[string]int32{
		"Compress_Algo_NONE":   0,
		"Compress_Algo_GZIP":   1,
		"Compress_Algo_ZSTD":   2,
		"Compress_Algo_SNAPPY": 3,
	}
)

func (x CompressAlgo) Enum() *CompressAlgo {
	p := new(CompressAlgo)
	*p = x
	return p
}

func (x CompressAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_message_proto_enumTypes[3].Descriptor()
}

func (CompressAlgo) Type() protoreflect.EnumType {
	return &file_v1_message_proto_enumTypes[3]
}

func (x CompressAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressAlgo.Descriptor instead.
func (CompressAlgo) EnumDescriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{3}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── 帧身份 ──────────────────────────────────────────────────────────────
	// version: 协议版本，用于平滑升级。当前 = 1。
	Version uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    SignalType `protobuf:"varint,2,opt,name=type,proto3,enum=gateway.v1.SignalType" json:"type,omitempty"`
	// msg_id: 发送方生成的全局唯一 ID（UUID v4 或雪花 ID）。
	//
	//	用途：① ACK 关联  ② 幂等去重（QoS-2）  ③ 追踪日志关联
	MsgId string `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// seq_id: 发送方单向单调递增序号。
	//
	//	用途：① 接收方检测丢包间隙  ② 断线重连时告知网关"从哪里补发"
	//	注意：与 msg_id 职责不同——msg_id 是全局唯一 ID，seq_id 是顺序标记。
	SeqId uint64 `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	// timestamp: 发送方时间戳，Unix 毫秒。
	//
	//	用途：① 端到端延迟度量  ② 客户端时钟校准（与 HandshakeAck.server_time 对比）
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ── 寻址 ────────────────────────────────────────────────────────────────
	// from: 发送方标识，格式 "{domain}:{uid}"，例如 "im:user_123"。
	//
	//	控制面消息（Ping/Handshake）可留空。
	From string `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	// to: 目标地址，支持 4 种 scheme：
	//
	//	"u:{uid}"       → 单用户，全设备扇出
	//	"r:{roomID}"    → 房间广播（直播弹幕）
	//	"t:{topic}"     → Pub/Sub Topic
	//	"g:{groupID}"   → 群组，网关侧解析成员列表
	//	"c:{connID}"    → 原始连接 ID（内部路由/调试）
	To string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	// ── 投递控制 ─────────────────────────────────────────────────────────────
	Qos QoS `protobuf:"varint,8,opt,name=qos,proto3,enum=gateway.v1.QoS" json:"qos,omitempty"`
	// ack_id: 网关向客户端回 ACK 时填写，值为被确认消息的 msg_id。
	//
	//	SDK 收到后从重试队列删除对应消息。
	AckId string `protobuf:"bytes,9,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	// expire_at: 绝对过期时间戳（Unix 毫秒）。为 0 表示永不过期。
	//
	//	使用绝对时间而非 TTL：消息经多节点转发时各节点判断结果一致。
	ExpireAt int64 `protobuf:"varint,10,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// offline: true = 目标离线时持久化，联网后补投。
	Offline bool `protobuf:"varint,11,opt,name=offline,proto3" json:"offline,omitempty"`
	// ── 路由提示（网关中间件读取，不透传给业务） ──────────────────────────────
	// biz_code: 业务域标识，用于网关侧 plugin 选择（限流策略、审核规则等）。
	//
	//	约定："im" | "push" | "live" | "custom.{name}"
	BizCode string `protobuf:"bytes,12,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`
	// trace_id: 分布式追踪 ID，跨服务传播。格式建议 W3C TraceContext。
	TraceId string `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// ── 编码提示（作用于 Body.payload） ──────────────────────────────────────
	// body_codec: Body.payload 的序列化格式。
	//
	//	接收方 unmarshal payload 前必须检查此字段。
	BodyCodec Codec `protobuf:"varint,14,opt,name=body_codec,json=bodyCodec,proto3,enum=gateway.v1.Codec" json:"body_codec,omitempty"`
	// compress: Body.payload 编码后的压缩算法。
	//
	//	解码顺序：先解压 → 再按 body_codec 反序列化。
	Compress CompressAlgo `protobuf:"varint,15,opt,name=compress,proto3,enum=gateway.v1.CompressAlgo" json:"compress,omitempty"`
	// ── 扩展 ─────────────────────────────────────────────────────────────────
	// headers: 中间件 K-V 元数据。网关 plugin 可读写。
	//
	//	Key 规范：小写，"x-" 前缀表示私有扩展。
	//	示例：{"x-retry-count":"2", "x-priority":"high", "x-content-type":"image"}
	Headers map[string]string `protobuf:"bytes,16,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body: 业务载荷容器。网关转发时不解析 body.payload。
	Body          *Body `protobuf:"bytes,17,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_Signal_Type_UNSPECIFIED
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetQos() QoS {
	if x != nil {
		return x.Qos
	}
	return QoS_QOS_AT_MOST_ONCE
}

func (x *Message) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

func (x *Message) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Message) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

func (x *Message) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

func (x *Message) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Message) GetBodyCodec() Codec {
	if x != nil {
		return x.BodyCodec
	}
	return Codec_Codec_UNSPECIFIED
}

func (x *Message) GetCompress() CompressAlgo {
	if x != nil {
		return x.Compress
	}
	return CompressAlgo_Compress_Algo_NONE
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

// Body 是业务载荷的容器。
// payload 对网关完全不透明——网关转发时不反序列化，只按外层字段路由。
type Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: 业务子类型字符串，由各域 SDK 定义。
	//
	//	IM:   "text" | "image" | "video" | "file" | "location" | "custom"
	//	Push: "alert" | "silent" | "badge"
	//	Live: "comment" | "gift" | "signal" | "pklive"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// payload: 按 Message.body_codec 编码、Message.compress 压缩后的字节。
	//
	//	网关：直接转发，不 unmarshal。
	//	SDK：按 body_codec 反序列化为 WellKnownPayload 或业务私有结构。
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// ext: 轻量扩展字段，存放不值得独立字段的元数据。
	//
	//	示例：{"mention_uids":"[\"u1\",\"u2\"]", "reply_to_mid":"msg_abc"}
	//	注意：value 存储为字符串（避免 Any 的额外 type_url 开销）。
	Ext           map[string]string `protobuf:"bytes,3,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Body) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Body) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Body) GetExt() map[string]string {
	if x != nil {
		return x.Ext
	}
	return nil
}

type WellKnownPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*WellKnownPayload_Handshake
	//	*WellKnownPayload_HandshakeAck
	//	*WellKnownPayload_Kick
	//	*WellKnownPayload_KickResponse
	//	*WellKnownPayload_Error
	//	*WellKnownPayload_Ack
	//	*WellKnownPayload_AuthRequest
	//	*WellKnownPayload_AuthResponse
	//	*WellKnownPayload_ImChat
	//	*WellKnownPayload_ImReceipt
	//	*WellKnownPayload_ImRevoke
	//	*WellKnownPayload_PushNotify
	//	*WellKnownPayload_LiveComment
	//	*WellKnownPayload_LiveGift
	//	*WellKnownPayload_Raw
	Content       isWellKnownPayload_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WellKnownPayload) Reset() {
	*x = WellKnownPayload{}
	mi := &file_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WellKnownPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WellKnownPayload) ProtoMessage() {}

func (x *WellKnownPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WellKnownPayload.ProtoReflect.Descriptor instead.
func (*WellKnownPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *WellKnownPayload) GetContent() isWellKnownPayload_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WellKnownPayload) GetHandshake() *HandshakePayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *WellKnownPayload) GetHandshakeAck() *HandshakeAckPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *WellKnownPayload) GetKick() *KickPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

func (x *WellKnownPayload) GetKickResponse() *KickResponsePayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_KickResponse); ok {
			return x.KickResponse
		}
	}
	return nil
}

func (x *WellKnownPayload) GetError() *ErrorPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WellKnownPayload) GetAck() *AckPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WellKnownPayload) GetAuthRequest() *AuthRequestPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *WellKnownPayload) GetAuthResponse() *AuthResponsePayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *WellKnownPayload) GetImChat() *IMChatPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_ImChat); ok {
			return x.ImChat
		}
	}
	return nil
}

func (x *WellKnownPayload) GetImReceipt() *IMReceiptPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_ImReceipt); ok {
			return x.ImReceipt
		}
	}
	return nil
}

func (x *WellKnownPayload) GetImRevoke() *IMRevokePayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_ImRevoke); ok {
			return x.ImRevoke
		}
	}
	return nil
}

func (x *WellKnownPayload) GetPushNotify() *PushNotifyPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_PushNotify); ok {
			return x.PushNotify
		}
	}
	return nil
}

func (x *WellKnownPayload) GetLiveComment() *LiveCommentPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_LiveComment); ok {
			return x.LiveComment
		}
	}
	return nil
}

func (x *WellKnownPayload) GetLiveGift() *LiveGiftPayload {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_LiveGift); ok {
			return x.LiveGift
		}
	}
	return nil
}

func (x *WellKnownPayload) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Content.(*WellKnownPayload_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isWellKnownPayload_Content interface {
	isWellKnownPayload_Content()
}

type WellKnownPayload_Handshake struct {
	// ── 控制面 ──────────────────────────────────────────────────────────
	Handshake *HandshakePayload `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type WellKnownPayload_HandshakeAck struct {
	HandshakeAck *HandshakeAckPayload `protobuf:"bytes,2,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"`
}

type WellKnownPayload_Kick struct {
	Kick *KickPayload `protobuf:"bytes,3,opt,name=kick,proto3,oneof"`
}

type WellKnownPayload_KickResponse struct {
	KickResponse *KickResponsePayload `protobuf:"bytes,4,opt,name=kick_response,json=kickResponse,proto3,oneof"`
}

type WellKnownPayload_Error struct {
	Error *ErrorPayload `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type WellKnownPayload_Ack struct {
	Ack *AckPayload `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type WellKnownPayload_AuthRequest struct {
	AuthRequest *AuthRequestPayload `protobuf:"bytes,7,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type WellKnownPayload_AuthResponse struct {
	AuthResponse *AuthResponsePayload `protobuf:"bytes,8,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type WellKnownPayload_ImChat struct {
	// ── IM 域 ────────────────────────────────────────────────────────────
	ImChat *IMChatPayload `protobuf:"bytes,10,opt,name=im_chat,json=imChat,proto3,oneof"`
}

type WellKnownPayload_ImReceipt struct {
	ImReceipt *IMReceiptPayload `protobuf:"bytes,11,opt,name=im_receipt,json=imReceipt,proto3,oneof"`
}

type WellKnownPayload_ImRevoke struct {
	ImRevoke *IMRevokePayload `protobuf:"bytes,12,opt,name=im_revoke,json=imRevoke,proto3,oneof"`
}

type WellKnownPayload_PushNotify struct {
	// ── Push 域 ──────────────────────────────────────────────────────────
	PushNotify *PushNotifyPayload `protobuf:"bytes,20,opt,name=push_notify,json=pushNotify,proto3,oneof"`
}

type WellKnownPayload_LiveComment struct {
	// ── Live 域 ──────────────────────────────────────────────────────────
	LiveComment *LiveCommentPayload `protobuf:"bytes,30,opt,name=live_comment,json=liveComment,proto3,oneof"`
}

type WellKnownPayload_LiveGift struct {
	LiveGift *LiveGiftPayload `protobuf:"bytes,31,opt,name=live_gift,json=liveGift,proto3,oneof"`
}

type WellKnownPayload_Raw struct {
	// ── 自定义 / 未来扩展 ────────────────────────────────────────────────
	// 业务方自定义 payload 请使用 field 100+ 并在业务 .proto 中 extend
	Raw []byte `protobuf:"bytes,99,opt,name=raw,proto3,oneof"` // 透传原始字节，用于网关不认识的业务 payload
}

func (*WellKnownPayload_Handshake) isWellKnownPayload_Content() {}

func (*WellKnownPayload_HandshakeAck) isWellKnownPayload_Content() {}

func (*WellKnownPayload_Kick) isWellKnownPayload_Content() {}

func (*WellKnownPayload_KickResponse) isWellKnownPayload_Content() {}

func (*WellKnownPayload_Error) isWellKnownPayload_Content() {}

func (*WellKnownPayload_Ack) isWellKnownPayload_Content() {}

func (*WellKnownPayload_AuthRequest) isWellKnownPayload_Content() {}

func (*WellKnownPayload_AuthResponse) isWellKnownPayload_Content() {}

func (*WellKnownPayload_ImChat) isWellKnownPayload_Content() {}

func (*WellKnownPayload_ImReceipt) isWellKnownPayload_Content() {}

func (*WellKnownPayload_ImRevoke) isWellKnownPayload_Content() {}

func (*WellKnownPayload_PushNotify) isWellKnownPayload_Content() {}

func (*WellKnownPayload_LiveComment) isWellKnownPayload_Content() {}

func (*WellKnownPayload_LiveGift) isWellKnownPayload_Content() {}

func (*WellKnownPayload_Raw) isWellKnownPayload_Content() {}

type HandshakePayload struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AppId      string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                // 多租户网关：标识应用
	Token      string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                             // 业务 auth 服务签发的短期 JWT
	DeviceId   string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备指纹，跨 session 稳定
	DeviceType string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // "ios" | "android" | "web" | "pc" | "iot"
	SdkVersion string                 `protobuf:"bytes,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"` // 能力协商用
	// last_seq_id: 客户端上次 session 收到的最高 SeqID。
	// 网关据此从 last_seq_id+1 开始补发离线消息（replay）。
	LastSeqId     uint64 `protobuf:"varint,6,opt,name=last_seq_id,json=lastSeqId,proto3" json:"last_seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakePayload) Reset() {
	*x = HandshakePayload{}
	mi := &file_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakePayload) ProtoMessage() {}

func (x *HandshakePayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakePayload.ProtoReflect.Descriptor instead.
func (*HandshakePayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakePayload) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HandshakePayload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HandshakePayload) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HandshakePayload) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *HandshakePayload) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HandshakePayload) GetLastSeqId() uint64 {
	if x != nil {
		return x.LastSeqId
	}
	return 0
}

type HandshakeAckPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnId            string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`                                   // 网关分配的连接唯一 ID
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                   // token 验证后解析出的用户 ID
	ServerTime        int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`                      // 服务器 Unix 毫秒，供客户端校准时钟偏差
	HeartbeatInterval int32                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // 建议心跳间隔（秒）
	MaxBodySize       int64                  `protobuf:"varint,5,opt,name=max_body_size,json=maxBodySize,proto3" json:"max_body_size,omitempty"`                 // 允许的最大 Body.payload 字节数
	ReplayFrom        uint64                 `protobuf:"varint,6,opt,name=replay_from,json=replayFrom,proto3" json:"replay_from,omitempty"`                      // 网关将从此 SeqID 开始补发（= last_seq_id + 1）
	// extensions: 网关声明支持的能力列表。
	//
	//	示例：["compress:zstd", "qos:2", "multi-device", "offline", "replay"]
	Extensions    []string `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAckPayload) Reset() {
	*x = HandshakeAckPayload{}
	mi := &file_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAckPayload) ProtoMessage() {}

func (x *HandshakeAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAckPayload.ProtoReflect.Descriptor instead.
func (*HandshakeAckPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeAckPayload) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *HandshakeAckPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HandshakeAckPayload) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HandshakeAckPayload) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *HandshakeAckPayload) GetMaxBodySize() int64 {
	if x != nil {
		return x.MaxBodySize
	}
	return 0
}

func (x *HandshakeAckPayload) GetReplayFrom() uint64 {
	if x != nil {
		return x.ReplayFrom
	}
	return 0
}

func (x *HandshakeAckPayload) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type AuthRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                             // 客户端提供的认证令牌
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                // 应用 ID
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备 ID
	DeviceType    string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // 设备类型
	BizCode       string                 `protobuf:"bytes,5,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`          // 业务代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequestPayload) Reset() {
	*x = AuthRequestPayload{}
	mi := &file_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequestPayload) ProtoMessage() {}

func (x *AuthRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequestPayload.ProtoReflect.Descriptor instead.
func (*AuthRequestPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRequestPayload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequestPayload) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AuthRequestPayload) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthRequestPayload) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *AuthRequestPayload) GetBizCode() string {
	if x != nil {
		return x.BizCode
	}
	return ""
}

type AuthResponsePayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                    // 响应，0 = 鉴权成功，非0 失败
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                                       // 状态描述
	Result            bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`                                                // 鉴权结果，true = 鉴权成功，false = 鉴权失败
	HeartbeatInternal uint32                 `protobuf:"varint,4,opt,name=heartbeat_internal,json=heartbeatInternal,proto3" json:"heartbeat_internal,omitempty"` // 服务端强制的心跳间隔（单位秒，默认 30s）
	SessionId         string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                          // 会话ID
	MaxBodySize       uint32                 `protobuf:"varint,6,opt,name=max_body_size,json=maxBodySize,proto3" json:"max_body_size,omitempty"`                 // 最大 body
	ReplayFrom        uint64                 `protobuf:"varint,7,opt,name=replay_from,json=replayFrom,proto3" json:"replay_from,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthResponsePayload) Reset() {
	*x = AuthResponsePayload{}
	mi := &file_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponsePayload) ProtoMessage() {}

func (x *AuthResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponsePayload.ProtoReflect.Descriptor instead.
func (*AuthResponsePayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponsePayload) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthResponsePayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthResponsePayload) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *AuthResponsePayload) GetHeartbeatInternal() uint32 {
	if x != nil {
		return x.HeartbeatInternal
	}
	return 0
}

func (x *AuthResponsePayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponsePayload) GetMaxBodySize() uint32 {
	if x != nil {
		return x.MaxBodySize
	}
	return 0
}

func (x *AuthResponsePayload) GetReplayFrom() uint64 {
	if x != nil {
		return x.ReplayFrom
	}
	return 0
}

type KickPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                           // 机器可读错误码
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                        // 人类可读原因（调试用）
	ReconnectAfter int32                  `protobuf:"varint,3,opt,name=reconnect_after,json=reconnectAfter,proto3" json:"reconnect_after,omitempty"` // >0 表示建议客户端等待 N 秒后重连（灰度发布用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickPayload) Reset() {
	*x = KickPayload{}
	mi := &file_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPayload) ProtoMessage() {}

func (x *KickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPayload.ProtoReflect.Descriptor instead.
func (*KickPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *KickPayload) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KickPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickPayload) GetReconnectAfter() int32 {
	if x != nil {
		return x.ReconnectAfter
	}
	return 0
}

type KickResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应，0 = 登出成功，非0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResponsePayload) Reset() {
	*x = KickResponsePayload{}
	mi := &file_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponsePayload) ProtoMessage() {}

func (x *KickResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponsePayload.ProtoReflect.Descriptor instead.
func (*KickResponsePayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *KickResponsePayload) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KickResponsePayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RefMsgId      string                 `protobuf:"bytes,3,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"` // 触发此错误的原始 msg_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorPayload) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorPayload) GetRefMsgId() string {
	if x != nil {
		return x.RefMsgId
	}
	return ""
}

type AckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefMsgId      string                 `protobuf:"bytes,1,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"` // 被确认的消息 msg_id
	RecvTime      int64                  `protobuf:"varint,2,opt,name=recv_time,json=recvTime,proto3" json:"recv_time,omitempty"`  // 网关收到时间（Unix 毫秒），供 RTT 度量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPayload) Reset() {
	*x = AckPayload{}
	mi := &file_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPayload) ProtoMessage() {}

func (x *AckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPayload.ProtoReflect.Descriptor instead.
func (*AckPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *AckPayload) GetRefMsgId() string {
	if x != nil {
		return x.RefMsgId
	}
	return ""
}

func (x *AckPayload) GetRecvTime() int64 {
	if x != nil {
		return x.RecvTime
	}
	return 0
}

type IMChatPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conv_id: 会话 ID。单聊 = 双方 uid 排序后拼接，群聊 = groupID。
	ConvId string `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	// content_type: "text" | "image" | "video" | "audio" | "file" | "location" | "custom"
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// content: 按 content_type 解析的实际内容，编码为 JSON bytes。
	//
	//	text:     {"text":"..."}
	//	image:    {"url":"...","width":1920,"height":1080}
	//	location: {"lat":31.2,"lng":121.4,"name":"..."}
	Content       []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mentions      []string `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty"`              // 被 @ 的 uid 列表
	ReplyTo       string   `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"` // 回复的消息 msg_id（Thread 支持）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMChatPayload) Reset() {
	*x = IMChatPayload{}
	mi := &file_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMChatPayload) ProtoMessage() {}

func (x *IMChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMChatPayload.ProtoReflect.Descriptor instead.
func (*IMChatPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *IMChatPayload) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *IMChatPayload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *IMChatPayload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IMChatPayload) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *IMChatPayload) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

type IMReceiptPayload struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ConvId string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	// receipt_type: "delivered" | "read"
	ReceiptType   string   `protobuf:"bytes,2,opt,name=receipt_type,json=receiptType,proto3" json:"receipt_type,omitempty"`
	MsgIds        []string `protobuf:"bytes,3,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`     // 被确认的消息 ID 列表
	ReadSeq       uint64   `protobuf:"varint,4,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"` // 已读水位线 SeqID（"已读到第 N 条"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMReceiptPayload) Reset() {
	*x = IMReceiptPayload{}
	mi := &file_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMReceiptPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMReceiptPayload) ProtoMessage() {}

func (x *IMReceiptPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMReceiptPayload.ProtoReflect.Descriptor instead.
func (*IMReceiptPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *IMReceiptPayload) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *IMReceiptPayload) GetReceiptType() string {
	if x != nil {
		return x.ReceiptType
	}
	return ""
}

func (x *IMReceiptPayload) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

func (x *IMReceiptPayload) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type IMRevokePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 被撤回的消息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMRevokePayload) Reset() {
	*x = IMRevokePayload{}
	mi := &file_v1_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMRevokePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMRevokePayload) ProtoMessage() {}

func (x *IMRevokePayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMRevokePayload.ProtoReflect.Descriptor instead.
func (*IMRevokePayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{13}
}

func (x *IMRevokePayload) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *IMRevokePayload) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type PushNotifyPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`  // 通知标题（silent push 时为空）
	Body  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`    // 通知正文
	Sound string                 `protobuf:"bytes,3,opt,name=sound,proto3" json:"sound,omitempty"`  // "default" | "" (静默) | 自定义音效名
	Badge int32                  `protobuf:"varint,4,opt,name=badge,proto3" json:"badge,omitempty"` // 角标数，-1 表示不变
	// data: 应用后台静默处理的 KV，不展示给用户
	Data map[string]string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// priority: "high"（立即唤醒设备）| "normal"
	Priority string `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	// collapse_key: 相同 key 的未投递 push 会被后来者覆盖（类似 FCM collapse_key）
	CollapseKey   string `protobuf:"bytes,7,opt,name=collapse_key,json=collapseKey,proto3" json:"collapse_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotifyPayload) Reset() {
	*x = PushNotifyPayload{}
	mi := &file_v1_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotifyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotifyPayload) ProtoMessage() {}

func (x *PushNotifyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotifyPayload.ProtoReflect.Descriptor instead.
func (*PushNotifyPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{14}
}

func (x *PushNotifyPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushNotifyPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushNotifyPayload) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *PushNotifyPayload) GetBadge() int32 {
	if x != nil {
		return x.Badge
	}
	return 0
}

func (x *PushNotifyPayload) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushNotifyPayload) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *PushNotifyPayload) GetCollapseKey() string {
	if x != nil {
		return x.CollapseKey
	}
	return ""
}

type LiveCommentPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"` // 付费彩色弹幕 hex 颜色值，例如 "#FF6600"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveCommentPayload) Reset() {
	*x = LiveCommentPayload{}
	mi := &file_v1_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveCommentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveCommentPayload) ProtoMessage() {}

func (x *LiveCommentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveCommentPayload.ProtoReflect.Descriptor instead.
func (*LiveCommentPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{15}
}

func (x *LiveCommentPayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LiveCommentPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LiveCommentPayload) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type LiveGiftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GiftId        string                 `protobuf:"bytes,2,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`
	GiftName      string                 `protobuf:"bytes,3,opt,name=gift_name,json=giftName,proto3" json:"gift_name,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	TotalCost     int64                  `protobuf:"varint,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"` // 网关校验后的虚拟货币总花费
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveGiftPayload) Reset() {
	*x = LiveGiftPayload{}
	mi := &file_v1_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveGiftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveGiftPayload) ProtoMessage() {}

func (x *LiveGiftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveGiftPayload.ProtoReflect.Descriptor instead.
func (*LiveGiftPayload) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{16}
}

func (x *LiveGiftPayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LiveGiftPayload) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *LiveGiftPayload) GetGiftName() string {
	if x != nil {
		return x.GiftName
	}
	return ""
}

func (x *LiveGiftPayload) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LiveGiftPayload) GetTotalCost() int64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

var File_v1_message_proto protoreflect.FileDescriptor

const file_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x10v1/message.proto\x12\n" +
	"gateway.v1\"\xec\x04\n" +
	"\aMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.gateway.v1.SignalTypeR\x04type\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\x12\x15\n" +
	"\x06seq_id\x18\x04 \x01(\x04R\x05seqId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04from\x18\x06 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\a \x01(\tR\x02to\x12!\n" +
	"\x03qos\x18\b \x01(\x0e2\x0f.gateway.v1.QoSR\x03qos\x12\x15\n" +
	"\x06ack_id\x18\t \x01(\tR\x05ackId\x12\x1b\n" +
	"\texpire_at\x18\n" +
	" \x01(\x03R\bexpireAt\x12\x18\n" +
	"\aoffline\x18\v \x01(\bR\aoffline\x12\x19\n" +
	"\bbiz_code\x18\f \x01(\tR\abizCode\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId\x120\n" +
	"\n" +
	"body_codec\x18\x0e \x01(\x0e2\x11.gateway.v1.CodecR\tbodyCodec\x124\n" +
	"\bcompress\x18\x0f \x01(\x0e2\x18.gateway.v1.CompressAlgoR\bcompress\x12:\n" +
	"\aheaders\x18\x10 \x03(\v2 .gateway.v1.Message.HeadersEntryR\aheaders\x12$\n" +
	"\x04body\x18\x11 \x01(\v2\x10.gateway.v1.BodyR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x04Body\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12+\n" +
	"\x03ext\x18\x03 \x03(\v2\x19.gateway.v1.Body.ExtEntryR\x03ext\x1a6\n" +
	"\bExtEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\a\n" +
	"\x10WellKnownPayload\x12<\n" +
	"\thandshake\x18\x01 \x01(\v2\x1c.gateway.v1.HandshakePayloadH\x00R\thandshake\x12F\n" +
	"\rhandshake_ack\x18\x02 \x01(\v2\x1f.gateway.v1.HandshakeAckPayloadH\x00R\fhandshakeAck\x12-\n" +
	"\x04kick\x18\x03 \x01(\v2\x17.gateway.v1.KickPayloadH\x00R\x04kick\x12F\n" +
	"\rkick_response\x18\x04 \x01(\v2\x1f.gateway.v1.KickResponsePayloadH\x00R\fkickResponse\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x18.gateway.v1.ErrorPayloadH\x00R\x05error\x12*\n" +
	"\x03ack\x18\x06 \x01(\v2\x16.gateway.v1.AckPayloadH\x00R\x03ack\x12C\n" +
	"\fauth_request\x18\a \x01(\v2\x1e.gateway.v1.AuthRequestPayloadH\x00R\vauthRequest\x12F\n" +
	"\rauth_response\x18\b \x01(\v2\x1f.gateway.v1.AuthResponsePayloadH\x00R\fauthResponse\x124\n" +
	"\aim_chat\x18\n" +
	" \x01(\v2\x19.gateway.v1.IMChatPayloadH\x00R\x06imChat\x12=\n" +
	"\n" +
	"im_receipt\x18\v \x01(\v2\x1c.gateway.v1.IMReceiptPayloadH\x00R\timReceipt\x12:\n" +
	"\tim_revoke\x18\f \x01(\v2\x1b.gateway.v1.IMRevokePayloadH\x00R\bimRevoke\x12@\n" +
	"\vpush_notify\x18\x14 \x01(\v2\x1d.gateway.v1.PushNotifyPayloadH\x00R\n" +
	"pushNotify\x12C\n" +
	"\flive_comment\x18\x1e \x01(\v2\x1e.gateway.v1.LiveCommentPayloadH\x00R\vliveComment\x12:\n" +
	"\tlive_gift\x18\x1f \x01(\v2\x1b.gateway.v1.LiveGiftPayloadH\x00R\bliveGift\x12\x12\n" +
	"\x03raw\x18c \x01(\fH\x00R\x03rawB\t\n" +
	"\acontent\"\xbe\x01\n" +
	"\x10HandshakePayload\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12\x1e\n" +
	"\vlast_seq_id\x18\x06 \x01(\x04R\tlastSeqId\"\xfc\x01\n" +
	"\x13HandshakeAckPayload\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x05R\x11heartbeatInterval\x12\"\n" +
	"\rmax_body_size\x18\x05 \x01(\x03R\vmaxBodySize\x12\x1f\n" +
	"\vreplay_from\x18\x06 \x01(\x04R\n" +
	"replayFrom\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x03(\tR\n" +
	"extensions\"\x9a\x01\n" +
	"\x12AuthRequestPayload\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x19\n" +
	"\bbiz_code\x18\x05 \x01(\tR\abizCode\"\xe6\x01\n" +
	"\x13AuthResponsePayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x12-\n" +
	"\x12heartbeat_internal\x18\x04 \x01(\rR\x11heartbeatInternal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\"\n" +
	"\rmax_body_size\x18\x06 \x01(\rR\vmaxBodySize\x12\x1f\n" +
	"\vreplay_from\x18\a \x01(\x04R\n" +
	"replayFrom\"b\n" +
	"\vKickPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0freconnect_after\x18\x03 \x01(\x05R\x0ereconnectAfter\";\n" +
	"\x13KickResponsePayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"Z\n" +
	"\fErrorPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\x03 \x01(\tR\brefMsgId\"G\n" +
	"\n" +
	"AckPayload\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\x01 \x01(\tR\brefMsgId\x12\x1b\n" +
	"\trecv_time\x18\x02 \x01(\x03R\brecvTime\"\x9c\x01\n" +
	"\rIMChatPayload\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1a\n" +
	"\bmentions\x18\x04 \x03(\tR\bmentions\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\tR\areplyTo\"\x82\x01\n" +
	"\x10IMReceiptPayload\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12!\n" +
	"\freceipt_type\x18\x02 \x01(\tR\vreceiptType\x12\x17\n" +
	"\amsg_ids\x18\x03 \x03(\tR\x06msgIds\x12\x19\n" +
	"\bread_seq\x18\x04 \x01(\x04R\areadSeq\"A\n" +
	"\x0fIMRevokePayload\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\"\x9e\x02\n" +
	"\x11PushNotifyPayload\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x14\n" +
	"\x05sound\x18\x03 \x01(\tR\x05sound\x12\x14\n" +
	"\x05badge\x18\x04 \x01(\x05R\x05badge\x12;\n" +
	"\x04data\x18\x05 \x03(\v2'.gateway.v1.PushNotifyPayload.DataEntryR\x04data\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12!\n" +
	"\fcollapse_key\x18\a \x01(\tR\vcollapseKey\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12LiveCommentPayload\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\x95\x01\n" +
	"\x0fLiveGiftPayload\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\agift_id\x18\x02 \x01(\tR\x06giftId\x12\x1b\n" +
	"\tgift_name\x18\x03 \x01(\tR\bgiftName\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x03R\ttotalCost*\x9d\x04\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17Signal_Type_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15Signal_Type_HANDSHAKE\x10\x01\x12\x1d\n" +
	"\x19Signal_Type_HANDSHAKE_ACK\x10\x02\x12\x14\n" +
	"\x10Signal_Type_PING\x10\x03\x12\x14\n" +
	"\x10Signal_Type_PONG\x10\x04\x12\x14\n" +
	"\x10Signal_Type_KICK\x10\x05\x12\x15\n" +
	"\x11Signal_Type_ERROR\x10\x06\x12\x13\n" +
	"\x0fSignal_Type_ACK\x10\a\x12\x14\n" +
	"\x10Signal_Type_DATA\x10d\x12\x17\n" +
	"\x13Signal_Type_IM_CHAT\x10e\x12\x1a\n" +
	"\x16Signal_Type_IM_RECEIPT\x10f\x12\x19\n" +
	"\x15Signal_Type_IM_REVOKE\x10g\x12\x19\n" +
	"\x15Signal_Type_IM_TYPING\x10h\x12\x1c\n" +
	"\x17Signal_Type_PUSH_NOTIFY\x10\xc9\x01\x12\x19\n" +
	"\x14Signal_Type_PUSH_ACK\x10\xca\x01\x12\x1a\n" +
	"\x15Signal_Type_LIVE_JOIN\x10\xad\x02\x12\x1b\n" +
	"\x16Signal_Type_LIVE_LEAVE\x10\xae\x02\x12\x1d\n" +
	"\x18Signal_Type_LIVE_COMMENT\x10\xaf\x02\x12\x1a\n" +
	"\x15Signal_Type_LIVE_GIFT\x10\xb0\x02\x12\x1c\n" +
	"\x17Signal_Type_LIVE_SIGNAL\x10\xb1\x02*H\n" +
	"\x03QoS\x12\x14\n" +
	"\x10QOS_AT_MOST_ONCE\x10\x00\x12\x15\n" +
	"\x11QOS_AT_LEAST_ONCE\x10\x01\x12\x14\n" +
	"\x10QOS_EXACTLY_ONCE\x10\x02*U\n" +
	"\x05Codec\x12\x15\n" +
	"\x11Codec_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"Codec_JSON\x10\x01\x12\x12\n" +
	"\x0eCodec_PROTOBUF\x10\x02\x12\x11\n" +
	"\rCodec_MSGPACK\x10\x03*p\n" +
	"\fCompressAlgo\x12\x16\n" +
	"\x12Compress_Algo_NONE\x10\x00\x12\x16\n" +
	"\x12Compress_Algo_GZIP\x10\x01\x12\x16\n" +
	"\x12Compress_Algo_ZSTD\x10\x02\x12\x18\n" +
	"\x14Compress_Algo_SNAPPY\x10\x03B0Z.github.com/vadam-zhan/long-gw/proto/v1;gatewayb\x06proto3"

var (
	file_v1_message_proto_rawDescOnce sync.Once
	file_v1_message_proto_rawDescData []byte
)

func file_v1_message_proto_rawDescGZIP() []byte {
	file_v1_message_proto_rawDescOnce.Do(func() {
		file_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)))
	})
	return file_v1_message_proto_rawDescData
}

var file_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1_message_proto_goTypes = []any{
	(SignalType)(0),             // 0: gateway.v1.SignalType
	(QoS)(0),                    // 1: gateway.v1.QoS
	(Codec)(0),                  // 2: gateway.v1.Codec
	(CompressAlgo)(0),           // 3: gateway.v1.CompressAlgo
	(*Message)(nil),             // 4: gateway.v1.Message
	(*Body)(nil),                // 5: gateway.v1.Body
	(*WellKnownPayload)(nil),    // 6: gateway.v1.WellKnownPayload
	(*HandshakePayload)(nil),    // 7: gateway.v1.HandshakePayload
	(*HandshakeAckPayload)(nil), // 8: gateway.v1.HandshakeAckPayload
	(*AuthRequestPayload)(nil),  // 9: gateway.v1.AuthRequestPayload
	(*AuthResponsePayload)(nil), // 10: gateway.v1.AuthResponsePayload
	(*KickPayload)(nil),         // 11: gateway.v1.KickPayload
	(*KickResponsePayload)(nil), // 12: gateway.v1.KickResponsePayload
	(*ErrorPayload)(nil),        // 13: gateway.v1.ErrorPayload
	(*AckPayload)(nil),          // 14: gateway.v1.AckPayload
	(*IMChatPayload)(nil),       // 15: gateway.v1.IMChatPayload
	(*IMReceiptPayload)(nil),    // 16: gateway.v1.IMReceiptPayload
	(*IMRevokePayload)(nil),     // 17: gateway.v1.IMRevokePayload
	(*PushNotifyPayload)(nil),   // 18: gateway.v1.PushNotifyPayload
	(*LiveCommentPayload)(nil),  // 19: gateway.v1.LiveCommentPayload
	(*LiveGiftPayload)(nil),     // 20: gateway.v1.LiveGiftPayload
	nil,                         // 21: gateway.v1.Message.HeadersEntry
	nil,                         // 22: gateway.v1.Body.ExtEntry
	nil,                         // 23: gateway.v1.PushNotifyPayload.DataEntry
}
var file_v1_message_proto_depIdxs = []int32{
	0,  // 0: gateway.v1.Message.type:type_name -> gateway.v1.SignalType
	1,  // 1: gateway.v1.Message.qos:type_name -> gateway.v1.QoS
	2,  // 2: gateway.v1.Message.body_codec:type_name -> gateway.v1.Codec
	3,  // 3: gateway.v1.Message.compress:type_name -> gateway.v1.CompressAlgo
	21, // 4: gateway.v1.Message.headers:type_name -> gateway.v1.Message.HeadersEntry
	5,  // 5: gateway.v1.Message.body:type_name -> gateway.v1.Body
	22, // 6: gateway.v1.Body.ext:type_name -> gateway.v1.Body.ExtEntry
	7,  // 7: gateway.v1.WellKnownPayload.handshake:type_name -> gateway.v1.HandshakePayload
	8,  // 8: gateway.v1.WellKnownPayload.handshake_ack:type_name -> gateway.v1.HandshakeAckPayload
	11, // 9: gateway.v1.WellKnownPayload.kick:type_name -> gateway.v1.KickPayload
	12, // 10: gateway.v1.WellKnownPayload.kick_response:type_name -> gateway.v1.KickResponsePayload
	13, // 11: gateway.v1.WellKnownPayload.error:type_name -> gateway.v1.ErrorPayload
	14, // 12: gateway.v1.WellKnownPayload.ack:type_name -> gateway.v1.AckPayload
	9,  // 13: gateway.v1.WellKnownPayload.auth_request:type_name -> gateway.v1.AuthRequestPayload
	10, // 14: gateway.v1.WellKnownPayload.auth_response:type_name -> gateway.v1.AuthResponsePayload
	15, // 15: gateway.v1.WellKnownPayload.im_chat:type_name -> gateway.v1.IMChatPayload
	16, // 16: gateway.v1.WellKnownPayload.im_receipt:type_name -> gateway.v1.IMReceiptPayload
	17, // 17: gateway.v1.WellKnownPayload.im_revoke:type_name -> gateway.v1.IMRevokePayload
	18, // 18: gateway.v1.WellKnownPayload.push_notify:type_name -> gateway.v1.PushNotifyPayload
	19, // 19: gateway.v1.WellKnownPayload.live_comment:type_name -> gateway.v1.LiveCommentPayload
	20, // 20: gateway.v1.WellKnownPayload.live_gift:type_name -> gateway.v1.LiveGiftPayload
	23, // 21: gateway.v1.PushNotifyPayload.data:type_name -> gateway.v1.PushNotifyPayload.DataEntry
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_v1_message_proto_init() }
func file_v1_message_proto_init() {
	if File_v1_message_proto != nil {
		return
	}
	file_v1_message_proto_msgTypes[2].OneofWrappers = []any{
		(*WellKnownPayload_Handshake)(nil),
		(*WellKnownPayload_HandshakeAck)(nil),
		(*WellKnownPayload_Kick)(nil),
		(*WellKnownPayload_KickResponse)(nil),
		(*WellKnownPayload_Error)(nil),
		(*WellKnownPayload_Ack)(nil),
		(*WellKnownPayload_AuthRequest)(nil),
		(*WellKnownPayload_AuthResponse)(nil),
		(*WellKnownPayload_ImChat)(nil),
		(*WellKnownPayload_ImReceipt)(nil),
		(*WellKnownPayload_ImRevoke)(nil),
		(*WellKnownPayload_PushNotify)(nil),
		(*WellKnownPayload_LiveComment)(nil),
		(*WellKnownPayload_LiveGift)(nil),
		(*WellKnownPayload_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_message_proto_goTypes,
		DependencyIndexes: file_v1_message_proto_depIdxs,
		EnumInfos:         file_v1_message_proto_enumTypes,
		MessageInfos:      file_v1_message_proto_msgTypes,
	}.Build()
	File_v1_message_proto = out.File
	file_v1_message_proto_goTypes = nil
	file_v1_message_proto_depIdxs = nil
}
