// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/message.proto

package gateway

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	// no validation rules for Type

	// no validation rules for MsgId

	// no validation rules for SeqId

	// no validation rules for Timestamp

	// no validation rules for From

	// no validation rules for To

	// no validation rules for Qos

	// no validation rules for AckId

	// no validation rules for ExpireAt

	// no validation rules for Offline

	// no validation rules for BizCode

	// no validation rules for TraceId

	// no validation rules for BodyCodec

	// no validation rules for Compress

	// no validation rules for Headers

	if all {
		switch v := interface{}(m.GetBody()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MessageValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MessageValidationError{
					field:  "Body",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on Body with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Body) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Body with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BodyMultiError, or nil if none found.
func (m *Body) ValidateAll() error {
	return m.validate(true)
}

func (m *Body) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Payload

	// no validation rules for Ext

	if len(errors) > 0 {
		return BodyMultiError(errors)
	}

	return nil
}

// BodyMultiError is an error wrapping multiple validation errors returned by
// Body.ValidateAll() if the designated constraints aren't met.
type BodyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BodyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BodyMultiError) AllErrors() []error { return m }

// BodyValidationError is the validation error returned by Body.Validate if the
// designated constraints aren't met.
type BodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BodyValidationError) ErrorName() string { return "BodyValidationError" }

// Error satisfies the builtin error interface
func (e BodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BodyValidationError{}

// Validate checks the field values on WellKnownPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WellKnownPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WellKnownPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WellKnownPayloadMultiError, or nil if none found.
func (m *WellKnownPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *WellKnownPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Content.(type) {
	case *WellKnownPayload_Handshake:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetHandshake()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Handshake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Handshake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHandshake()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "Handshake",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_HandshakeAck:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetHandshakeAck()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "HandshakeAck",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "HandshakeAck",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHandshakeAck()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "HandshakeAck",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_Kick:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetKick()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Kick",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Kick",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetKick()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "Kick",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_Error:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetError()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_Ack:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetAck()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Ack",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "Ack",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAck()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "Ack",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_ImChat:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetImChat()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImChat",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImChat",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetImChat()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "ImChat",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_ImReceipt:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetImReceipt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImReceipt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImReceipt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetImReceipt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "ImReceipt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_ImRevoke:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetImRevoke()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImRevoke",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "ImRevoke",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetImRevoke()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "ImRevoke",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_PushNotify:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPushNotify()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "PushNotify",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "PushNotify",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPushNotify()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "PushNotify",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_LiveComment:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetLiveComment()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "LiveComment",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "LiveComment",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLiveComment()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "LiveComment",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_LiveGift:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetLiveGift()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "LiveGift",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WellKnownPayloadValidationError{
						field:  "LiveGift",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLiveGift()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WellKnownPayloadValidationError{
					field:  "LiveGift",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *WellKnownPayload_Raw:
		if v == nil {
			err := WellKnownPayloadValidationError{
				field:  "Content",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Raw
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return WellKnownPayloadMultiError(errors)
	}

	return nil
}

// WellKnownPayloadMultiError is an error wrapping multiple validation errors
// returned by WellKnownPayload.ValidateAll() if the designated constraints
// aren't met.
type WellKnownPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WellKnownPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WellKnownPayloadMultiError) AllErrors() []error { return m }

// WellKnownPayloadValidationError is the validation error returned by
// WellKnownPayload.Validate if the designated constraints aren't met.
type WellKnownPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WellKnownPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WellKnownPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WellKnownPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WellKnownPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WellKnownPayloadValidationError) ErrorName() string { return "WellKnownPayloadValidationError" }

// Error satisfies the builtin error interface
func (e WellKnownPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWellKnownPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WellKnownPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WellKnownPayloadValidationError{}

// Validate checks the field values on HandshakePayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HandshakePayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HandshakePayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HandshakePayloadMultiError, or nil if none found.
func (m *HandshakePayload) ValidateAll() error {
	return m.validate(true)
}

func (m *HandshakePayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AppId

	// no validation rules for Token

	// no validation rules for DeviceId

	// no validation rules for DeviceType

	// no validation rules for SdkVersion

	// no validation rules for LastSeqId

	if len(errors) > 0 {
		return HandshakePayloadMultiError(errors)
	}

	return nil
}

// HandshakePayloadMultiError is an error wrapping multiple validation errors
// returned by HandshakePayload.ValidateAll() if the designated constraints
// aren't met.
type HandshakePayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HandshakePayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HandshakePayloadMultiError) AllErrors() []error { return m }

// HandshakePayloadValidationError is the validation error returned by
// HandshakePayload.Validate if the designated constraints aren't met.
type HandshakePayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandshakePayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandshakePayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandshakePayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandshakePayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandshakePayloadValidationError) ErrorName() string { return "HandshakePayloadValidationError" }

// Error satisfies the builtin error interface
func (e HandshakePayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandshakePayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandshakePayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandshakePayloadValidationError{}

// Validate checks the field values on HandshakeAckPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HandshakeAckPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HandshakeAckPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HandshakeAckPayloadMultiError, or nil if none found.
func (m *HandshakeAckPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *HandshakeAckPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnId

	// no validation rules for UserId

	// no validation rules for ServerTime

	// no validation rules for HeartbeatInterval

	// no validation rules for MaxBodySize

	// no validation rules for ReplayFrom

	if len(errors) > 0 {
		return HandshakeAckPayloadMultiError(errors)
	}

	return nil
}

// HandshakeAckPayloadMultiError is an error wrapping multiple validation
// errors returned by HandshakeAckPayload.ValidateAll() if the designated
// constraints aren't met.
type HandshakeAckPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HandshakeAckPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HandshakeAckPayloadMultiError) AllErrors() []error { return m }

// HandshakeAckPayloadValidationError is the validation error returned by
// HandshakeAckPayload.Validate if the designated constraints aren't met.
type HandshakeAckPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandshakeAckPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandshakeAckPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandshakeAckPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandshakeAckPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandshakeAckPayloadValidationError) ErrorName() string {
	return "HandshakeAckPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e HandshakeAckPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandshakeAckPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandshakeAckPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandshakeAckPayloadValidationError{}

// Validate checks the field values on KickPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KickPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KickPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KickPayloadMultiError, or
// nil if none found.
func (m *KickPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *KickPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for ReconnectAfter

	if len(errors) > 0 {
		return KickPayloadMultiError(errors)
	}

	return nil
}

// KickPayloadMultiError is an error wrapping multiple validation errors
// returned by KickPayload.ValidateAll() if the designated constraints aren't met.
type KickPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KickPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KickPayloadMultiError) AllErrors() []error { return m }

// KickPayloadValidationError is the validation error returned by
// KickPayload.Validate if the designated constraints aren't met.
type KickPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KickPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KickPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KickPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KickPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KickPayloadValidationError) ErrorName() string { return "KickPayloadValidationError" }

// Error satisfies the builtin error interface
func (e KickPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKickPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KickPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KickPayloadValidationError{}

// Validate checks the field values on ErrorPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorPayloadMultiError, or
// nil if none found.
func (m *ErrorPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for RefMsgId

	if len(errors) > 0 {
		return ErrorPayloadMultiError(errors)
	}

	return nil
}

// ErrorPayloadMultiError is an error wrapping multiple validation errors
// returned by ErrorPayload.ValidateAll() if the designated constraints aren't met.
type ErrorPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorPayloadMultiError) AllErrors() []error { return m }

// ErrorPayloadValidationError is the validation error returned by
// ErrorPayload.Validate if the designated constraints aren't met.
type ErrorPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorPayloadValidationError) ErrorName() string { return "ErrorPayloadValidationError" }

// Error satisfies the builtin error interface
func (e ErrorPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorPayloadValidationError{}

// Validate checks the field values on AckPayload with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AckPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AckPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AckPayloadMultiError, or
// nil if none found.
func (m *AckPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *AckPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RefMsgId

	// no validation rules for RecvTime

	if len(errors) > 0 {
		return AckPayloadMultiError(errors)
	}

	return nil
}

// AckPayloadMultiError is an error wrapping multiple validation errors
// returned by AckPayload.ValidateAll() if the designated constraints aren't met.
type AckPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AckPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AckPayloadMultiError) AllErrors() []error { return m }

// AckPayloadValidationError is the validation error returned by
// AckPayload.Validate if the designated constraints aren't met.
type AckPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AckPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AckPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AckPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AckPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AckPayloadValidationError) ErrorName() string { return "AckPayloadValidationError" }

// Error satisfies the builtin error interface
func (e AckPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAckPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AckPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AckPayloadValidationError{}

// Validate checks the field values on IMChatPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IMChatPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IMChatPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IMChatPayloadMultiError, or
// nil if none found.
func (m *IMChatPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *IMChatPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConvId

	// no validation rules for ContentType

	// no validation rules for Content

	// no validation rules for ReplyTo

	if len(errors) > 0 {
		return IMChatPayloadMultiError(errors)
	}

	return nil
}

// IMChatPayloadMultiError is an error wrapping multiple validation errors
// returned by IMChatPayload.ValidateAll() if the designated constraints
// aren't met.
type IMChatPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IMChatPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IMChatPayloadMultiError) AllErrors() []error { return m }

// IMChatPayloadValidationError is the validation error returned by
// IMChatPayload.Validate if the designated constraints aren't met.
type IMChatPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IMChatPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IMChatPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IMChatPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IMChatPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IMChatPayloadValidationError) ErrorName() string { return "IMChatPayloadValidationError" }

// Error satisfies the builtin error interface
func (e IMChatPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIMChatPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IMChatPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IMChatPayloadValidationError{}

// Validate checks the field values on IMReceiptPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IMReceiptPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IMReceiptPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IMReceiptPayloadMultiError, or nil if none found.
func (m *IMReceiptPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *IMReceiptPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConvId

	// no validation rules for ReceiptType

	// no validation rules for ReadSeq

	if len(errors) > 0 {
		return IMReceiptPayloadMultiError(errors)
	}

	return nil
}

// IMReceiptPayloadMultiError is an error wrapping multiple validation errors
// returned by IMReceiptPayload.ValidateAll() if the designated constraints
// aren't met.
type IMReceiptPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IMReceiptPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IMReceiptPayloadMultiError) AllErrors() []error { return m }

// IMReceiptPayloadValidationError is the validation error returned by
// IMReceiptPayload.Validate if the designated constraints aren't met.
type IMReceiptPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IMReceiptPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IMReceiptPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IMReceiptPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IMReceiptPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IMReceiptPayloadValidationError) ErrorName() string { return "IMReceiptPayloadValidationError" }

// Error satisfies the builtin error interface
func (e IMReceiptPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIMReceiptPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IMReceiptPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IMReceiptPayloadValidationError{}

// Validate checks the field values on IMRevokePayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IMRevokePayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IMRevokePayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IMRevokePayloadMultiError, or nil if none found.
func (m *IMRevokePayload) ValidateAll() error {
	return m.validate(true)
}

func (m *IMRevokePayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConvId

	// no validation rules for MsgId

	if len(errors) > 0 {
		return IMRevokePayloadMultiError(errors)
	}

	return nil
}

// IMRevokePayloadMultiError is an error wrapping multiple validation errors
// returned by IMRevokePayload.ValidateAll() if the designated constraints
// aren't met.
type IMRevokePayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IMRevokePayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IMRevokePayloadMultiError) AllErrors() []error { return m }

// IMRevokePayloadValidationError is the validation error returned by
// IMRevokePayload.Validate if the designated constraints aren't met.
type IMRevokePayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IMRevokePayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IMRevokePayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IMRevokePayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IMRevokePayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IMRevokePayloadValidationError) ErrorName() string { return "IMRevokePayloadValidationError" }

// Error satisfies the builtin error interface
func (e IMRevokePayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIMRevokePayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IMRevokePayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IMRevokePayloadValidationError{}

// Validate checks the field values on PushNotifyPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PushNotifyPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushNotifyPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PushNotifyPayloadMultiError, or nil if none found.
func (m *PushNotifyPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *PushNotifyPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Body

	// no validation rules for Sound

	// no validation rules for Badge

	// no validation rules for Data

	// no validation rules for Priority

	// no validation rules for CollapseKey

	if len(errors) > 0 {
		return PushNotifyPayloadMultiError(errors)
	}

	return nil
}

// PushNotifyPayloadMultiError is an error wrapping multiple validation errors
// returned by PushNotifyPayload.ValidateAll() if the designated constraints
// aren't met.
type PushNotifyPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushNotifyPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushNotifyPayloadMultiError) AllErrors() []error { return m }

// PushNotifyPayloadValidationError is the validation error returned by
// PushNotifyPayload.Validate if the designated constraints aren't met.
type PushNotifyPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushNotifyPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushNotifyPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushNotifyPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushNotifyPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushNotifyPayloadValidationError) ErrorName() string {
	return "PushNotifyPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e PushNotifyPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushNotifyPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushNotifyPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushNotifyPayloadValidationError{}

// Validate checks the field values on LiveCommentPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LiveCommentPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LiveCommentPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LiveCommentPayloadMultiError, or nil if none found.
func (m *LiveCommentPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *LiveCommentPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoomId

	// no validation rules for Content

	// no validation rules for Color

	if len(errors) > 0 {
		return LiveCommentPayloadMultiError(errors)
	}

	return nil
}

// LiveCommentPayloadMultiError is an error wrapping multiple validation errors
// returned by LiveCommentPayload.ValidateAll() if the designated constraints
// aren't met.
type LiveCommentPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LiveCommentPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LiveCommentPayloadMultiError) AllErrors() []error { return m }

// LiveCommentPayloadValidationError is the validation error returned by
// LiveCommentPayload.Validate if the designated constraints aren't met.
type LiveCommentPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LiveCommentPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LiveCommentPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LiveCommentPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LiveCommentPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LiveCommentPayloadValidationError) ErrorName() string {
	return "LiveCommentPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e LiveCommentPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLiveCommentPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LiveCommentPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LiveCommentPayloadValidationError{}

// Validate checks the field values on LiveGiftPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LiveGiftPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LiveGiftPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LiveGiftPayloadMultiError, or nil if none found.
func (m *LiveGiftPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *LiveGiftPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoomId

	// no validation rules for GiftId

	// no validation rules for GiftName

	// no validation rules for Count

	// no validation rules for TotalCost

	if len(errors) > 0 {
		return LiveGiftPayloadMultiError(errors)
	}

	return nil
}

// LiveGiftPayloadMultiError is an error wrapping multiple validation errors
// returned by LiveGiftPayload.ValidateAll() if the designated constraints
// aren't met.
type LiveGiftPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LiveGiftPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LiveGiftPayloadMultiError) AllErrors() []error { return m }

// LiveGiftPayloadValidationError is the validation error returned by
// LiveGiftPayload.Validate if the designated constraints aren't met.
type LiveGiftPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LiveGiftPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LiveGiftPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LiveGiftPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LiveGiftPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LiveGiftPayloadValidationError) ErrorName() string { return "LiveGiftPayloadValidationError" }

// Error satisfies the builtin error interface
func (e LiveGiftPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLiveGiftPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LiveGiftPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LiveGiftPayloadValidationError{}
